#include "Z80.h"

void Z80::initInstructions()
{
	using c = Z80;
	using a = AddressingModes;

	rootInstructions =
	{
		{"NOP", a::IMP, &c::NOP, 4},
		{"LD BC,nn", a::IMX, &c::LDDDNN, 10},
		{"LD (BC),A", a::IMP, &c::LDBCA, 7},
		{"INC BC", a::IMP, &c::INCSS, 6},
		{"INC B", a::IMP, &c::INCR, 4},
		{"DEC B", a::IMP, &c::DECR, 4},
		{"LD B,n", a::IMM, &c::LDRN, 7},
		{"RLCA", a::IMP, &c::RLCA, 4},
		{"EX AF,AF'", a::IMP, &c::EXAFAF, 4},
		{"ADD HL,BC", a::IMP, &c::ADDHLSS, 11},
		{"LD A,(BC)", a::IDX, &c::LDABC, 7},
		{"DEC BC", a::IMP, &c::DECSS, 6},
		{"INC C", a::IMP, &c::INCR, 4},
		{"DEC C", a::IMP, &c::DECR, 4},
		{"LD C,n", a::IMM, &c::LDRN, 7},
		{"RRCA", a::IMP, &c::RRCA, 4},
		{"DJNZ e", a::REL, &c::DJNZE, 8},
		{"LD DE,nn", a::IMX, &c::LDDDNN, 10},
		{"LD (DE),A", a::IMP, &c::LDDEA, 7},
		{"INC DE", a::IMP, &c::INCSS, 6},
		{"INC D", a::IMP, &c::INCR, 4},
		{"DEC D", a::IMP, &c::DECR, 4},
		{"LD D,n", a::IMM, &c::LDRN, 7},
		{"RLA", a::IMP, &c::RLA, 4},
		{"JR e", a::REL, &c::JRE, 12},
		{"ADD HL,DE", a::IMP, &c::ADDHLSS, 11},
		{"LD A,(DE)", a::IDX, &c::LDADE, 7},
		{"DEC DE", a::IMP, &c::DECSS, 6},
		{"INC E", a::IMP, &c::INCR, 4},
		{"DEC E", a::IMP, &c::DECR, 4},
		{"LD E,n", a::IMM, &c::LDRN, 7},
		{"RRA", a::IMP, &c::RRA, 4},
		{"JR NZ,e", a::REL, &c::JRNZE, 7},
		{"LD HL,nn", a::IMX, &c::LDDDNN, 10},
		{"LD (nn),HL", a::IMX, &c::LDNNHL, 16},
		{"INC HL", a::IMP, &c::INCSS, 6},
		{"INC H", a::IMP, &c::INCR, 4},
		{"DEC H", a::IMP, &c::DECR, 4},
		{"LD H,n", a::IMM, &c::LDRN, 7},
		{"DAA", a::IMP, &c::DAA, 4},
		{"JR Z,e", a::REL, &c::JRZE, 7},
		{"ADD HL,HL", a::IMP, &c::ADDHLSS, 11},
		{"LD HL,(nn)", a::IMX, &c::LDHLNN, 16},
		{"DEC HL", a::IMP, &c::DECSS, 6},
		{"INC L", a::IMP, &c::INCR, 4},
		{"DEC L", a::IMP, &c::DECR, 4},
		{"LD L,n", a::IMM, &c::LDRN, 7},
		{"CPL", a::IMP, &c::CPL, 4},
		{"JR NC,e", a::REL, &c::JRNCE, 7},
		{"LD SP,nn", a::IMX, &c::LDDDNN, 10},
		{"LD (nn),A", a::IMX, &c::LDNNA, 13},
		{"INC SP", a::IMP, &c::INCSS, 6},
		{"INC (HL)", a::RGIHL, &c::INCHL, 11},
		{"DEC (HL)", a::RGIHL, &c::DECHL, 11},
		{"LD (HL),n", a::IMM, &c::LDHLN, 10},
		{"SCF", a::IMP, &c::SCF, 4},
		{"JR C,e", a::REL, &c::JRCE, 7},
		{"ADD HL,SP", a::IMP, &c::ADDHLSS, 11},
		{"LD A,(nn)", a::IMX, &c::LDANN, 13},
		{"DEC SP", a::IMP, &c::DECSS, 6},
		{"INC A", a::IMP, &c::INCR, 4},
		{"DEC A", a::IMP, &c::DECR, 4},
		{"LD A,n", a::IMM, &c::LDRN, 7},
		{"CCF", a::IMP, &c::CCF, 4},
		{"LD B,B", a::REG, &c::LDRR, 4},
		{"LD B,C", a::REG, &c::LDRR, 4},
		{"LD B,D", a::REG, &c::LDRR, 4},
		{"LD B,E", a::REG, &c::LDRR, 4},
		{"LD B,H", a::REG, &c::LDRR, 4},
		{"LD B,L", a::REG, &c::LDRR, 4},
		{"LD B,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD B,A", a::REG, &c::LDRR, 4},
		{"LD C,B", a::REG, &c::LDRR, 4},
		{"LD C,C", a::REG, &c::LDRR, 4},
		{"LD C,D", a::REG, &c::LDRR, 4},
		{"LD C,E", a::REG, &c::LDRR, 4},
		{"LD C,H", a::REG, &c::LDRR, 4},
		{"LD C,L", a::REG, &c::LDRR, 4},
		{"LD C,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD C,A", a::REG, &c::LDRR, 4},
		{"LD D,B", a::REG, &c::LDRR, 4},
		{"LD D,C", a::REG, &c::LDRR, 4},
		{"LD D,D", a::REG, &c::LDRR, 4},
		{"LD D,E", a::REG, &c::LDRR, 4},
		{"LD D,H", a::REG, &c::LDRR, 4},
		{"LD D,L", a::REG, &c::LDRR, 4},
		{"LD D,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD D,A", a::REG, &c::LDRR, 4},
		{"LD E,B", a::REG, &c::LDRR, 4},
		{"LD E,C", a::REG, &c::LDRR, 4},
		{"LD E,D", a::REG, &c::LDRR, 4},
		{"LD E,E", a::REG, &c::LDRR, 4},
		{"LD E,H", a::REG, &c::LDRR, 4},
		{"LD E,L", a::REG, &c::LDRR, 4},
		{"LD E,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD E,A", a::REG, &c::LDRR, 4},
		{"LD H,B", a::REG, &c::LDRR, 4},
		{"LD H,C", a::REG, &c::LDRR, 4},
		{"LD H,D", a::REG, &c::LDRR, 4},
		{"LD H,E", a::REG, &c::LDRR, 4},
		{"LD H,H", a::REG, &c::LDRR, 4},
		{"LD H,L", a::REG, &c::LDRR, 4},
		{"LD H,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD H,A", a::REG, &c::LDRR, 4},
		{"LD L,B", a::REG, &c::LDRR, 4},
		{"LD L,C", a::REG, &c::LDRR, 4},
		{"LD L,D", a::REG, &c::LDRR, 4},
		{"LD L,E", a::REG, &c::LDRR, 4},
		{"LD L,H", a::REG, &c::LDRR, 4},
		{"LD L,L", a::REG, &c::LDRR, 4},
		{"LD L,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD L,A", a::REG, &c::LDRR, 4},
		{"LD (HL),B", a::IMP, &c::LDHLR, 7},
		{"LD (HL),C", a::IMP, &c::LDHLR, 7},
		{"LD (HL),D", a::IMP, &c::LDHLR, 7},
		{"LD (HL),E", a::IMP, &c::LDHLR, 7},
		{"LD (HL),H", a::IMP, &c::LDHLR, 7},
		{"LD (HL),L", a::IMP, &c::LDHLR, 7},
		{"HALT", a::IMP, &c::HALT, 4},
		{"LD (HL),A", a::IMP, &c::LDHLR, 7},
		{"LD A,B", a::REG, &c::LDRR, 4},
		{"LD A,C", a::REG, &c::LDRR, 4},
		{"LD A,D", a::REG, &c::LDRR, 4},
		{"LD A,E", a::REG, &c::LDRR, 4},
		{"LD A,H", a::REG, &c::LDRR, 4},
		{"LD A,L", a::REG, &c::LDRR, 4},
		{"LD A,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD A,A", a::REG, &c::LDRR, 4},
		{"ADD A,B", a::REG, &c::ADDAR, 4},
		{"ADD A,C", a::REG, &c::ADDAR, 4},
		{"ADD A,D", a::REG, &c::ADDAR, 4},
		{"ADD A,E", a::REG, &c::ADDAR, 4},
		{"ADD A,H", a::REG, &c::ADDAR, 4},
		{"ADD A,L", a::REG, &c::ADDAR, 4},
		{"ADD A,(HL)", a::RGIHL, &c::ADDAHL, 7},
		{"ADD A,A", a::REG, &c::ADDAR, 4},
		{"ADC A,B", a::REG, &c::ADCAR, 4},
		{"ADC A,C", a::REG, &c::ADCAR, 4},
		{"ADC A,D", a::REG, &c::ADCAR, 4},
		{"ADC A,E", a::REG, &c::ADCAR, 4},
		{"ADC A,H", a::REG, &c::ADCAR, 4},
		{"ADC A,L", a::REG, &c::ADCAR, 4},
		{"ADC A,(HL)", a::RGIHL, &c::ADCAHL, 7},
		{"ADC A,A", a::REG, &c::ADCAR, 4},
		{"SUB A,B", a::REG, &c::SUBR, 4},
		{"SUB A,C", a::REG, &c::SUBR, 4},
		{"SUB A,D", a::REG, &c::SUBR, 4},
		{"SUB A,E", a::REG, &c::SUBR, 4},
		{"SUB A,H", a::REG, &c::SUBR, 4},
		{"SUB A,L", a::REG, &c::SUBR, 4},
		{"SUB A,(HL)", a::RGIHL, &c::SUBHL, 7},
		{"SUB A,A", a::REG, &c::SUBR, 4},
		{"SBC A,B", a::REG, &c::SBCAR, 4},
		{"SBC A,C", a::REG, &c::SBCAR, 4},
		{"SBC A,D", a::REG, &c::SBCAR, 4},
		{"SBC A,E", a::REG, &c::SBCAR, 4},
		{"SBC A,H", a::REG, &c::SBCAR, 4},
		{"SBC A,L", a::REG, &c::SBCAR, 4},
		{"SBC A,(HL)", a::RGIHL, &c::SBCAHL, 7},
		{"SBC A,A", a::REG, &c::SBCAR, 4},
		{"AND B", a::IMP, &c::ANDR, 4},
		{"AND C", a::IMP, &c::ANDR, 4},
		{"AND D", a::IMP, &c::ANDR, 4},
		{"AND E", a::IMP, &c::ANDR, 4},
		{"AND H", a::IMP, &c::ANDR, 4},
		{"AND L", a::IMP, &c::ANDR, 4},
		{"AND (HL)", a::RGIHL, &c::ANDHL, 7},
		{"AND A", a::IMP, &c::ANDR, 4},
		{"XOR B", a::IMP, &c::XORR, 4},
		{"XOR C", a::IMP, &c::XORR, 4},
		{"XOR D", a::IMP, &c::XORR, 4},
		{"XOR E", a::IMP, &c::XORR, 4},
		{"XOR H", a::IMP, &c::XORR, 4},
		{"XOR L", a::IMP, &c::XORR, 4},
		{"XOR (HL)", a::RGIHL, &c::XORHL, 7},
		{"XOR A", a::IMP, &c::XORR, 4},
		{"OR B", a::IMP, &c::ORR, 4},
		{"OR C", a::IMP, &c::ORR, 4},
		{"OR D", a::IMP, &c::ORR, 4},
		{"OR E", a::IMP, &c::ORR, 4},
		{"OR H", a::IMP, &c::ORR, 4},
		{"OR L", a::IMP, &c::ORR, 4},
		{"OR (HL)", a::RGIHL, &c::ORHL, 7},
		{"OR A", a::IMP, &c::ORR, 4},
		{"CP B", a::IMP, &c::CPR, 4},
		{"CP C", a::IMP, &c::CPR, 4},
		{"CP D", a::IMP, &c::CPR, 4},
		{"CP E", a::IMP, &c::CPR, 4},
		{"CP H", a::IMP, &c::CPR, 4},
		{"CP L", a::IMP, &c::CPR, 4},
		{"BP (HL)", a::RGIHL, &c::CPHL, 7},
		{"CP A", a::IMP, &c::CPR, 4},
		{"RET NZ", a::IMP, &c::RETCC, 5},
		{"POP BC", a::IMP, &c::POPQQ, 10},
		{"JP NZ,nn", a::IMX, &c::JPCCNN, 10},
		{"JP nn", a::IMX, &c::JPNN, 10},
		{"CALL NZ,nn", a::IMX, &c::CALLCCNN, 10},
		{"PUSH BC", a::IMP, &c::PUSHQQ, 11},
		{"ADD A,n", a::IMM, &c::ADDAN, 7},
		{"RST &00", a::IMP, &c::RSTP, 11},
		{"RET Z", a::IMP, &c::RETCC, 5},
		{"RET", a::IMP, &c::RET, 10},
		{"JP Z,nn", a::IMX, &c::JPCCNN, 10},
		{"???", a::IMP, &c::XXX, 4},
		{"CALL Z,nn", a::IMX, &c::CALLCCNN, 10},
		{"CALL nn", a::IMX, &c::CALLNN, 17},
		{"ADC A,n", a::IMM, &c::ADCAN, 7},
		{"RST &08", a::IMP, &c::RSTP, 11},
		{"RET NC", a::IMP, &c::RETCC, 5},
		{"POP DE", a::IMP, &c::POPQQ, 10},
		{"JP NC,nn", a::IMX, &c::JPCCNN, 10},
		{"OUT (n),A", a::IMM, &c::OUTNA, 11},
		{"CALL NC,nn", a::IMX, &c::CALLCCNN, 10},
		{"PUSH DE", a::IMP, &c::PUSHQQ, 11},
		{"SUB A,n", a::IMM, &c::SUBN, 7},
		{"RST &10", a::IMP, &c::RSTP, 11},
		{"RET Z", a::IMP, &c::RETCC, 5},
		{"EXX", a::IMP, &c::EXX, 4},
		{"JP C,nn", a::IMX, &c::JPCCNN, 10},
		{"IN A,(n)", a::IMM, &c::INAN, 11},
		{"CALL C,nn", a::IMX, &c::CALLCCNN, 10},
		{"???", a::IMP, &c::XXX, 4},
		{"SBC A,n", a::IMM, &c::SBCAN, 7},
		{"RST &18", a::IMP, &c::RSTP, 11},
		{"RET PO", a::IMP, &c::RETCC, 5},
		{"POP HL", a::IMP, &c::POPQQ, 10},
		{"JP PO,nn", a::IMX, &c::JPCCNN, 10},
		{"EX (SP),HL", a::IMP, &c::EXSPHL, 19},
		{"CALL PO,nn", a::IMX, &c::CALLCCNN, 10},
		{"PUSH HL", a::IMP, &c::PUSHQQ, 11},
		{"AND n", a::IMM, &c::ANDN, 7},
		{"RST &20", a::IMP, &c::RSTP, 11},
		{"RET PE", a::IMP, &c::RETCC, 5},
		{"JP (HL)", a::IMP, &c::JPHL, 4},
		{"JP PE,nn", a::IMX, &c::JPCCNN, 10},
		{"EX DE,HL", a::IMP, &c::EXDEHL, 4},
		{"CALL PE,nn", a::IMX, &c::CALLCCNN, 10},
		{"???", a::IMP, &c::XXX, 4},
		{"XOR n", a::IMM, &c::XORN, 7},
		{"RST &28", a::IMP, &c::RSTP, 11},
		{"RET P", a::IMP, &c::RETCC, 5},
		{"POP AF", a::IMP, &c::POPQQ, 10},
		{"JP P,nn", a::IMX, &c::JPCCNN, 10},
		{"DI", a::IMP, &c::DI, 4},
		{"CALL P,nn", a::IMX, &c::CALLCCNN, 10},
		{"PUSH AF", a::IMP, &c::PUSHQQ, 11},
		{"OR n", a::IMM, &c::ORN, 7},
		{"RST &30", a::IMP, &c::RSTP, 11},
		{"RET M", a::IMP, &c::RETCC, 5},
		{"LD SP,HL", a::IMP, &c::LDSPHL, 6},
		{"JP M,nn",a::IMX, &c::JPCCNN, 10},
		{"EI", a::IMP, &c::EI, 4},
		{"CALL M,nn", a::IMX, &c::CALLCCNN, 10},
		{ "???", a::IMP, &c::XXX, 4 },
		{"CP n", a::IMM, &c::CPN, 7},
		{"RST &38", a::IMP, &c::RSTP, 11},
	};

	edInstructions =
	{
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"IN B,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),B", a::IMP, &c::OUTCR, 12},
		{"SBC HL,BC", a::IMP, &c::SBCHLSS, 15},
		{"LD (nn),BC", a::IMX, &c::LDNNDD, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 0", a::IMP, &c::IM0, 8},
		{"ADD I,A", a::REG, &c::LDIA, 9},
		{"IN C,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),C", a::IMP, &c::OUTCR, 12},
		{"ADC HL,BC", a::IMP, &c::ADCHLSS, 15},
		{"LD BC,(nn)", a::IMM, &c::LDDDFNN, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETI", a::IMP, &c::RETI, 14},
		{"IM 0", a::IMP, &c::IM0, 8},
		{"LD R,A", a::REG, &c::LDRA, 9},
		{"IN D,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),D", a::IMP, &c::OUTCR, 12},
		{"SBC HL,DE", a::IMP, &c::SBCHLSS, 15},
		{"LD (nn),DE", a::IMX, &c::LDNNDD, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 1", a::IMP, &c::IM1, 8},
		{"LD A,I", a::REG, &c::LDAI, 9},
		{"IN D,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),E", a::IMP, &c::OUTCR, 12},
		{"ADC HL,DE", a::IMP, &c::ADCHLSS, 15},
		{"LD DE,(nn)", a::IMX, &c::LDDDFNN, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 2", a::IMP, &c::IM2, 8},
		{"LD A,R", a::REG, &c::LDAR, 9},
		{"IN H,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),H", a::IMP, &c::OUTCR, 12},
		{"SBC HL,HL", a::IMP, &c::SBCHLSS, 15},
		{"LD (nn),HL", a::IMX, &c::LDNNDD, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 0", a::IMP, &c::IM0, 8},
		{"RRD", a::RGIHL, &c::RRD, 18},
		{"IN L,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),L", a::IMP, &c::OUTCR, 12},
		{"ADC HL,HL", a::IMP, &c::ADCHLSS, 15},
		{"LD HL,(nn)", a::IMX, &c::LDDDFNN, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 0", a::IMP, &c::IM0, 8},
		{"RLD", a::RGIHL, &c::RLD, 18},
		{"IN F,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),F", a::IMP, &c::OUTCR, 12},
		{"SBC HL,SP", a::IMP, &c::SBCHLSS, 15},
		{"LD (nn),SP", a::IMX, &c::LDNNDD, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 1", a::IMP, &c::IM1, 8},
		{"???", a::IMP, &c::XXX, 4},
		{"IN A,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),A", a::IMP, &c::OUTCR, 12},
		{"ADC HL,SP", a::IMP, &c::ADCHLSS, 15},
		{"LD SP,(nn)", a::IMX, &c::LDDDFNN, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 2", a::IMP, &c::IM2, 8},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LDI", a::IMP, &c::LDI, 16},
		{"CPI", a::IMP, &c::CPI, 16},
		{"INI", a::IMP, &c::INI, 16},
		{"OUTI", a::IMP, &c::OUTI, 16},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LDD", a::IMP, &c::LDD, 16},
		{"CPD", a::IMP, &c::CPD, 16},
		{"IND", a::IMP, &c::IND, 16},
		{"OUTD", a::IMP, &c::OUTD, 16},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LDIR", a::IMP, &c::LDIR, 16},
		{"CPIR", a::IMP, &c::CPIR, 16},
		{"INIR", a::IMP, &c::INIR, 16},
		{"OTIR", a::IMP, &c::OTIR, 16},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LDDR", a::IMP, &c::LDDR, 16},
		{"CPDR", a::IMP, &c::CPDR, 16},
		{"INDR", a::IMP, &c::INDR, 16},
		{"OTDR", a::IMP, &c::OTDR, 16},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
	};

	cbInstructions =
	{
		{"RLC B", a::IMP, &c::RLCR, 8},
		{"RLC C", a::IMP, &c::RLCR, 8},
		{"RLC D", a::IMP, &c::RLCR, 8},
		{"RLC E", a::IMP, &c::RLCR, 8},
		{"RLC H", a::IMP, &c::RLCR, 8},
		{"RLC L", a::IMP, &c::RLCR, 8},
		{"RLC (HL)", a::RGIHL, &c::RLCHL, 15},
		{"RLC A", a::IMP, &c::RLCR, 8},
		{"RRC B", a::IMP, &c::RRCR, 8},
		{"RRC C", a::IMP, &c::RRCR, 8},
		{"RRC D", a::IMP, &c::RRCR, 8},
		{"RRC E", a::IMP, &c::RRCR, 8},
		{"RRC H", a::IMP, &c::RRCR, 8},
		{"RRC L", a::IMP, &c::RRCR, 8},
		{"RRC (HL)", a::RGIHL, &c::RRCHL, 15},
		{"RRC A", a::IMP, &c::RRCR, 8},
		{"RL B", a::IMP, &c::RLR, 8},
		{"RL C", a::IMP, &c::RLR, 8},
		{"RL D", a::IMP, &c::RLR, 8},
		{"RL E", a::IMP, &c::RLR, 8},
		{"RL H", a::IMP, &c::RLR, 8},
		{"RL L", a::IMP, &c::RLR, 8},
		{"RL (HL)", a::RGIHL, &c::RLHL, 15},
		{"RL A", a::IMP, &c::RLR, 8},
		{"RR B", a::IMP, &c::RRR, 8},
		{"RR C", a::IMP, &c::RRR, 8},
		{"RR D", a::IMP, &c::RRR, 8},
		{"RR E", a::IMP, &c::RRR, 8},
		{"RR H", a::IMP, &c::RRR, 8},
		{"RR L", a::IMP, &c::RRR, 8},
		{"RR (HL)", a::RGIHL, &c::RRHL, 15},
		{"RR A", a::IMP, &c::RRR, 8},
		{"SLA B", a::IMP, &c::SLAR, 8},
		{"SLA C", a::IMP, &c::SLAR, 8},
		{"SLA D", a::IMP, &c::SLAR, 8},
		{"SLA E", a::IMP, &c::SLAR, 8},
		{"SLA H", a::IMP, &c::SLAR, 8},
		{"SLA L", a::IMP, &c::SLAR, 8},
		{"SLA (HL)", a::RGIHL, &c::SLAHL, 15},
		{"SLA A", a::IMP, &c::SLAR, 8},
		{"SRA B", a::IMP, &c::SRAR, 8},
		{"SRA C", a::IMP, &c::SRAR, 8},
		{"SRA D", a::IMP, &c::SRAR, 8},
		{"SRA E", a::IMP, &c::SRAR, 8},
		{"SRA H", a::IMP, &c::SRAR, 8},
		{"SRA L", a::IMP, &c::SRAR, 8},
		{"SRA (HL)", a::RGIHL, &c::SRAHL, 15},
		{"SRA A", a::IMP, &c::SRAR, 8},
		{"SLS B", a::IMP, &c::SLSR, 8},
		{"SLS C", a::IMP, &c::SLSR, 8},
		{"SLS D", a::IMP, &c::SLSR, 8},
		{"SLS E", a::IMP, &c::SLSR, 8},
		{"SLS H", a::IMP, &c::SLSR, 8},
		{"SLS L", a::IMP, &c::SLSR, 8},
		{"SLS (HL)", a::RGIHL, &c::SLSHL, 15},
		{"SLS A", a::IMP, &c::SLSR, 8},
		{"SRL B", a::IMP, &c::SRLR, 8},
		{"SRL C", a::IMP, &c::SRLR, 8},
		{"SRL D", a::IMP, &c::SRLR, 8},
		{"SRL E", a::IMP, &c::SRLR, 8},
		{"SRL H", a::IMP, &c::SRLR, 8},
		{"SRL L", a::IMP, &c::SRLR, 8},
		{"SRL (HL)", a::RGIHL, &c::SRLHL, 15},
		{"SRL A", a::IMP, &c::SRLR, 8},
		{"BIT 0,B", a::IMP, &c::BITBR, 8},
		{"BIT 0,C", a::IMP, &c::BITBR, 8},
		{"BIT 0,D", a::IMP, &c::BITBR, 8},
		{"BIT 0,E", a::IMP, &c::BITBR, 8},
		{"BIT 0,H", a::IMP, &c::BITBR, 8},
		{"BIT 0,L", a::IMP, &c::BITBR, 8},
		{"BIT 0,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 0,A", a::IMP, &c::BITBR, 8},
		{"BIT 1,B", a::IMP, &c::BITBR, 8},
		{"BIT 1,C", a::IMP, &c::BITBR, 8},
		{"BIT 1,D", a::IMP, &c::BITBR, 8},
		{"BIT 1,E", a::IMP, &c::BITBR, 8},
		{"BIT 1,H", a::IMP, &c::BITBR, 8},
		{"BIT 1,L", a::IMP, &c::BITBR, 8},
		{"BIT 1,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 1,A", a::IMP, &c::BITBR, 8},
		{"BIT 2,B", a::IMP, &c::BITBR, 8},
		{"BIT 2,C", a::IMP, &c::BITBR, 8},
		{"BIT 2,D", a::IMP, &c::BITBR, 8},
		{"BIT 2,E", a::IMP, &c::BITBR, 8},
		{"BIT 2,H", a::IMP, &c::BITBR, 8},
		{"BIT 2,L", a::IMP, &c::BITBR, 8},
		{"BIT 2,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 2,A", a::IMP, &c::BITBR, 8},
		{"BIT 3,B", a::IMP, &c::BITBR, 8},
		{"BIT 3,C", a::IMP, &c::BITBR, 8},
		{"BIT 3,D", a::IMP, &c::BITBR, 8},
		{"BIT 3,E", a::IMP, &c::BITBR, 8},
		{"BIT 3,H", a::IMP, &c::BITBR, 8},
		{"BIT 3,L", a::IMP, &c::BITBR, 8},
		{"BIT 3,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 3,A", a::IMP, &c::BITBR, 8},
		{"BIT 4,B", a::IMP, &c::BITBR, 8},
		{"BIT 4,C", a::IMP, &c::BITBR, 8},
		{"BIT 4,D", a::IMP, &c::BITBR, 8},
		{"BIT 4,E", a::IMP, &c::BITBR, 8},
		{"BIT 4,H", a::IMP, &c::BITBR, 8},
		{"BIT 4,L", a::IMP, &c::BITBR, 8},
		{"BIT 4,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 4,A", a::IMP, &c::BITBR, 8},
		{"BIT 5,B", a::IMP, &c::BITBR, 8},
		{"BIT 5,C", a::IMP, &c::BITBR, 8},
		{"BIT 5,D", a::IMP, &c::BITBR, 8},
		{"BIT 5,E", a::IMP, &c::BITBR, 8},
		{"BIT 5,H", a::IMP, &c::BITBR, 8},
		{"BIT 5,L", a::IMP, &c::BITBR, 8},
		{"BIT 5,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 5,A", a::IMP, &c::BITBR, 8},
		{"BIT 6,B", a::IMP, &c::BITBR, 8},
		{"BIT 6,C", a::IMP, &c::BITBR, 8},
		{"BIT 6,D", a::IMP, &c::BITBR, 8},
		{"BIT 6,E", a::IMP, &c::BITBR, 8},
		{"BIT 6,H", a::IMP, &c::BITBR, 8},
		{"BIT 6,L", a::IMP, &c::BITBR, 8},
		{"BIT 6,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 6,A", a::IMP, &c::BITBR, 8},
		{"BIT 7,B", a::IMP, &c::BITBR, 8},
		{"BIT 7,C", a::IMP, &c::BITBR, 8},
		{"BIT 7,D", a::IMP, &c::BITBR, 8},
		{"BIT 7,E", a::IMP, &c::BITBR, 8},
		{"BIT 7,H", a::IMP, &c::BITBR, 8},
		{"BIT 7,L", a::IMP, &c::BITBR, 8},
		{"BIT 7,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 7,A", a::IMP, &c::BITBR, 8},
		{"RES 0,B", a::IMP, &c::RESBR, 8},
		{"RES 0,C", a::IMP, &c::RESBR, 8},
		{"RES 0,D", a::IMP, &c::RESBR, 8},
		{"RES 0,E", a::IMP, &c::RESBR, 8},
		{"RES 0,H", a::IMP, &c::RESBR, 8},
		{"RES 0,L", a::IMP, &c::RESBR, 8},
		{"RES 0,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 0,A", a::IMP, &c::RESBR, 8},
		{"RES 1,B", a::IMP, &c::RESBR, 8},
		{"RES 1,C", a::IMP, &c::RESBR, 8},
		{"RES 1,D", a::IMP, &c::RESBR, 8},
		{"RES 1,E", a::IMP, &c::RESBR, 8},
		{"RES 1,H", a::IMP, &c::RESBR, 8},
		{"RES 1,L", a::IMP, &c::RESBR, 8},
		{"RES 1,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 1,A", a::IMP, &c::RESBR, 8},
		{"RES 2,B", a::IMP, &c::RESBR, 8},
		{"RES 2,C", a::IMP, &c::RESBR, 8},
		{"RES 2,D", a::IMP, &c::RESBR, 8},
		{"RES 2,E", a::IMP, &c::RESBR, 8},
		{"RES 2,H", a::IMP, &c::RESBR, 8},
		{"RES 2,L", a::IMP, &c::RESBR, 8},
		{"RES 2,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 2,A", a::IMP, &c::RESBR, 8},
		{"RES 3,B", a::IMP, &c::RESBR, 8},
		{"RES 3,C", a::IMP, &c::RESBR, 8},
		{"RES 3,D", a::IMP, &c::RESBR, 8},
		{"RES 3,E", a::IMP, &c::RESBR, 8},
		{"RES 3,H", a::IMP, &c::RESBR, 8},
		{"RES 3,L", a::IMP, &c::RESBR, 8},
		{"RES 3,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 3,A", a::IMP, &c::RESBR, 8},
		{"RES 4,B", a::IMP, &c::RESBR, 8},
		{"RES 4,C", a::IMP, &c::RESBR, 8},
		{"RES 4,D", a::IMP, &c::RESBR, 8},
		{"RES 4,E", a::IMP, &c::RESBR, 8},
		{"RES 4,H", a::IMP, &c::RESBR, 8},
		{"RES 4,L", a::IMP, &c::RESBR, 8},
		{"RES 4,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 4,A", a::IMP, &c::RESBR, 8},
		{"RES 5,B", a::IMP, &c::RESBR, 8},
		{"RES 5,C", a::IMP, &c::RESBR, 8},
		{"RES 5,D", a::IMP, &c::RESBR, 8},
		{"RES 5,E", a::IMP, &c::RESBR, 8},
		{"RES 5,H", a::IMP, &c::RESBR, 8},
		{"RES 5,L", a::IMP, &c::RESBR, 8},
		{"RES 5,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 5,A", a::IMP, &c::RESBR, 8},
		{"RES 6,B", a::IMP, &c::RESBR, 8},
		{"RES 6,C", a::IMP, &c::RESBR, 8},
		{"RES 6,D", a::IMP, &c::RESBR, 8},
		{"RES 6,E", a::IMP, &c::RESBR, 8},
		{"RES 6,H", a::IMP, &c::RESBR, 8},
		{"RES 6,L", a::IMP, &c::RESBR, 8},
		{"RES 6,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 6,A", a::IMP, &c::RESBR, 8},
		{"RES 7,B", a::IMP, &c::RESBR, 8},
		{"RES 7,C", a::IMP, &c::RESBR, 8},
		{"RES 7,D", a::IMP, &c::RESBR, 8},
		{"RES 7,E", a::IMP, &c::RESBR, 8},
		{"RES 7,H", a::IMP, &c::RESBR, 8},
		{"RES 7,L", a::IMP, &c::RESBR, 8},
		{"RES 7,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 7,A", a::IMP, &c::RESBR, 8},
		{"SET 0,B", a::IMP, &c::SETBR, 8},
		{"SET 0,C", a::IMP, &c::SETBR, 8},
		{"SET 0,D", a::IMP, &c::SETBR, 8},
		{"SET 0,E", a::IMP, &c::SETBR, 8},
		{"SET 0,H", a::IMP, &c::SETBR, 8},
		{"SET 0,L", a::IMP, &c::SETBR, 8},
		{"SET 0,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 0,A", a::IMP, &c::SETBR, 8},
		{"SET 1,B", a::IMP, &c::SETBR, 8},
		{"SET 1,C", a::IMP, &c::SETBR, 8},
		{"SET 1,D", a::IMP, &c::SETBR, 8},
		{"SET 1,E", a::IMP, &c::SETBR, 8},
		{"SET 1,H", a::IMP, &c::SETBR, 8},
		{"SET 1,L", a::IMP, &c::SETBR, 8},
		{"SET 1,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 1,A", a::IMP, &c::SETBR, 8},
		{"SET 2,B", a::IMP, &c::SETBR, 8},
		{"SET 2,C", a::IMP, &c::SETBR, 8},
		{"SET 2,D", a::IMP, &c::SETBR, 8},
		{"SET 2,E", a::IMP, &c::SETBR, 8},
		{"SET 2,H", a::IMP, &c::SETBR, 8},
		{"SET 2,L", a::IMP, &c::SETBR, 8},
		{"SET 2,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 2,A", a::IMP, &c::SETBR, 8},
		{"SET 3,B", a::IMP, &c::SETBR, 8},
		{"SET 3,C", a::IMP, &c::SETBR, 8},
		{"SET 3,D", a::IMP, &c::SETBR, 8},
		{"SET 3,E", a::IMP, &c::SETBR, 8},
		{"SET 3,H", a::IMP, &c::SETBR, 8},
		{"SET 3,L", a::IMP, &c::SETBR, 8},
		{"SET 3,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 3,A", a::IMP, &c::SETBR, 8},
		{"SET 4,B", a::IMP, &c::SETBR, 8},
		{"SET 4,C", a::IMP, &c::SETBR, 8},
		{"SET 4,D", a::IMP, &c::SETBR, 8},
		{"SET 4,E", a::IMP, &c::SETBR, 8},
		{"SET 4,H", a::IMP, &c::SETBR, 8},
		{"SET 4,L", a::IMP, &c::SETBR, 8},
		{"SET 4,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 4,A", a::IMP, &c::SETBR, 8},
		{"SET 5,B", a::IMP, &c::SETBR, 8},
		{"SET 5,C", a::IMP, &c::SETBR, 8},
		{"SET 5,D", a::IMP, &c::SETBR, 8},
		{"SET 5,E", a::IMP, &c::SETBR, 8},
		{"SET 5,H", a::IMP, &c::SETBR, 8},
		{"SET 5,L", a::IMP, &c::SETBR, 8},
		{"SET 5,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 5,A", a::IMP, &c::SETBR, 8},
		{"SET 6,B", a::IMP, &c::SETBR, 8},
		{"SET 6,C", a::IMP, &c::SETBR, 8},
		{"SET 6,D", a::IMP, &c::SETBR, 8},
		{"SET 6,E", a::IMP, &c::SETBR, 8},
		{"SET 6,H", a::IMP, &c::SETBR, 8},
		{"SET 6,L", a::IMP, &c::SETBR, 8},
		{"SET 6,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 6,A", a::IMP, &c::SETBR, 8},
		{"SET 7,B", a::IMP, &c::SETBR, 8},
		{"SET 7,C", a::IMP, &c::SETBR, 8},
		{"SET 7,D", a::IMP, &c::SETBR, 8},
		{"SET 7,E", a::IMP, &c::SETBR, 8},
		{"SET 7,H", a::IMP, &c::SETBR, 8},
		{"SET 7,L", a::IMP, &c::SETBR, 8},
		{"SET 7,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 7,A", a::IMP, &c::SETBR, 8},
	};

	irInstructions =
	{
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IR,BC", a::IMP, &c::ADDIRPP, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IR,DE", a::IMP, &c::ADDIRPP, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD IR,nn", a::IMX, &c::LDIRNN, 14},
		{"LD (nn),IR", a::IMX, &c::LDNNIR, 20},
		{"INC IR", a::IMP, &c::INCIR, 10},
		{"INC IRh", a::IMP, &c::INCIRH, 8},
		{"DEC IRh", a::IMP, &c::DECIRH, 8},
		{"LD IRh,n", a::IMM, &c::LDIRHN, 11},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IR,IR", a::IMP, &c::ADDIRPP, 15},
		{"LD IR,(nn)", a::IMX, &c::LDIRFNN, 20},
		{"DEC IR", a::IMP, &c::DECIR, 10},
		{"INC IRl", a::IMP, &c::INCIRL, 8},
		{"DEC IRl", a::IMP, &c::DECIRL, 8},
		{"LD IRl,n", a::IMM, &c::LDIRLN, 11},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"INC (IR+d)", a::REL, &c::INCIRD, 23},
		{"DEC (IR+d)", a::REL, &c::DECIRD, 23},
		{"LD (IR+d),n", a::REL, &c::LDIRDN, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IR,SP", a::IMP, &c::ADDIRPP, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD B,IRh", a::IMP, &c::LDRIRH, 8},
		{"LD B,IRl", a::IMP, &c::LDRIRL, 8},
		{"LD B,(IR+d)", a::REL, &c::LDRIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD C,IRh", a::IMP, &c::LDRIRH, 8},
		{"LD C,IRl", a::IMP, &c::LDRIRL, 8},
		{"LD C,(IR+d)", a::REL, &c::LDRIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD D,IRh", a::IMP, &c::LDRIRH, 8},
		{"LD D,IRl", a::IMP, &c::LDRIRL, 8},
		{"LD D,(IR+d)", a::REL, &c::LDRIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD E,IRh", a::IMP, &c::LDRIRH, 8},
		{"LD E,IRl", a::IMP, &c::LDRIRL, 8},
		{"LD E,(IR+d)", a::REL, &c::LDRIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"LD IRh,B", a::IMP, &c::LDIRHR, 8},
		{"LD IRh,C", a::IMP, &c::LDIRHR, 8},
		{"LD IRh,D", a::IMP, &c::LDIRHR, 8},
		{"LD IRh,E", a::IMP, &c::LDIRHR, 8},
		{"LD IRh,IRh", a::IMP, &c::LDIRHIRH, 8},
		{"LD IRh,IRl", a::IMP, &c::LDIRHIRL, 8},
		{"LD H,(IR+d)", a::REL, &c::LDRIRD, 19},
		{"LD IRh,A", a::IMP, &c::LDIRHR, 8},
		{"LD IRl,B", a::IMP, &c::LDIRLR, 8},
		{"LD IRl,C", a::IMP, &c::LDIRLR, 8},
		{"LD IRl,D", a::IMP, &c::LDIRLR, 8},
		{"LD IRl,E", a::IMP, &c::LDIRLR, 8},
		{"LD IRl,IRh", a::IMP, &c::LDIRLIRH, 8},
		{"LD IRl,IRl", a::IMP, &c::LDIRLIRL, 8},
		{"LD L,(IR+d)", a::REL, &c::LDRIRD, 19},
		{"LD IRl,A", a::IMP, &c::LDIRLR, 8},
		{"LD (IR+d),B", a::REL, &c::LDIRDR, 19},
		{"LD (IR+d),C", a::REL, &c::LDIRDR, 19},
		{"LD (IR+d),D", a::REL, &c::LDIRDR, 19},
		{"LD (IR+d),E", a::REL, &c::LDIRDR, 19},
		{"LD (IR+d),H", a::REL, &c::LDIRDR, 19},
		{"LD (IR+d),L", a::REL, &c::LDIRDR, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"LD (IR+d),A", a::REL, &c::LDIRDR, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD A,IRh", a::IMP, &c::LDRIRH, 8},
		{"LD A,IRl", a::IMP, &c::LDRIRL, 8},
		{"LD A,(IR+d)", a::REL, &c::LDRIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD A,IRH", a::IMP, &c::ADDAIRH, 8},
		{"ADD A,IRL", a::IMP, &c::ADDAIRL, 8},
		{"ADD A,(IR+d)", a::REL, &c::ADDAIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADC A,IRH", a::IMP, &c::ADCAIRH, 8},
		{"ADC A,IRL", a::IMP, &c::ADCAIRL, 8},
		{"ADC A,(IR+d)", a::REL, &c::ADCAIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"SUB A,IRH", a::IMP, &c::SUBAIRH, 8},
		{"SUB A,IRL", a::IMP, &c::SUBAIRL, 8},
		{"SUB A,(IR+d)", a::REL, &c::SUBIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"SBC A,IRH", a::IMP, &c::SBCAIRH, 8},
		{"SBC A,IRL", a::IMP, &c::SBCAIRL, 8},
		{"SBC A,(IR+d)", a::REL, &c::SBCAIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"AND IRH", a::IMP, &c::ANDIRH, 8},
		{"AND IRL", a::IMP, &c::ANDIRL, 8},
		{"AND (IR+d)", a::REL, &c::ANDIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"XOR IRH", a::IMP, &c::XORIRH, 8},
		{"XOR IRL", a::IMP, &c::XORIRL, 8},
		{"XOR (IR+d)", a::REL, &c::XORIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"OR IRH", a::IMP, &c::ORIRH, 8},
		{"OR IRL", a::IMP, &c::ORIRL, 8},
		{"OR (IR+d)", a::REL, &c::ORIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"CP IRH", a::IMP, &c::CPIRH, 8},
		{"CP IRL", a::IMP, &c::CPIRL, 8},
		{"CP (IR+d)", a::REL, &c::CPIRD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"POP IR", a::IMP, &c::POPIR, 14},
		{"???", a::IMP, &c::XXX, 4},
		{"EX (SP),IR", a::IMP, &c::EXSPIR, 23},
		{"???", a::IMP, &c::XXX, 4},
		{"PUSH IR", a::IMP, &c::PUSHIR, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"JP (IR)", a::IMP, &c::JPIR, 8},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD SP,IR", a::IMP, &c::LDSPIR, 10},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
	};

	ircbInstructions =
	{
		{"RLC (IR+d),B", a::RELS, &c::RLCIRD, 23},
		{"RLC (IR+d),C", a::RELS, &c::RLCIRD, 23},
		{"RLC (IR+d),D", a::RELS, &c::RLCIRD, 23},
		{"RLC (IR+d),E", a::RELS, &c::RLCIRD, 23},
		{"RLC (IR+d),H", a::RELS, &c::RLCIRD, 23},
		{"RLC (IR+d),L", a::RELS, &c::RLCIRD, 23},
		{"RLC (IR+d)", a::RELS, &c::RLCIRD, 23},
		{"RLC (IR+d),A", a::RELS, &c::RLCIRD, 23},
		{"RRC (IR+d),B", a::RELS, &c::RRCIRD, 23},
		{"RRC (IR+d),C", a::RELS, &c::RRCIRD, 23},
		{"RRC (IR+d),D", a::RELS, &c::RRCIRD, 23},
		{"RRC (IR+d),E", a::RELS, &c::RRCIRD, 23},
		{"RRC (IR+d),H", a::RELS, &c::RRCIRD, 23},
		{"RRC (IR+d),L", a::RELS, &c::RRCIRD, 23},
		{"RRC (IR+d)", a::RELS, &c::RRCIRD, 23},
		{"RRC (IR+d),A", a::RELS, &c::RRCIRD, 23},
		{"RL (IR+d),B", a::RELS, &c::RLIRD, 23},
		{"RL (IR+d),C", a::RELS, &c::RLIRD, 23},
		{"RL (IR+d),D", a::RELS, &c::RLIRD, 23},
		{"RL (IR+d),E", a::RELS, &c::RLIRD, 23},
		{"RL (IR+d),H", a::RELS, &c::RLIRD, 23},
		{"RL (IR+d),L", a::RELS, &c::RLIRD, 23},
		{"RL (IR+d)", a::RELS, &c::RLIRD, 23},
		{"RL (IR+d),A", a::RELS, &c::RLIRD, 23},
		{"RR (IR+d),B", a::RELS, &c::RRIRD, 23},
		{"RR (IR+d),C", a::RELS, &c::RRIRD, 23},
		{"RR (IR+d),D", a::RELS, &c::RRIRD, 23},
		{"RR (IR+d),E", a::RELS, &c::RRIRD, 23},
		{"RR (IR+d),H", a::RELS, &c::RRIRD, 23},
		{"RR (IR+d),L", a::RELS, &c::RRIRD, 23},
		{"RR (IR+d)", a::RELS, &c::RRIRD, 23},
		{"RR (IR+d),A", a::RELS, &c::RRIRD, 23},
		{"SLA (IR+d),B", a::RELS, &c::SLAIRD, 23},
		{"SLA (IR+d),C", a::RELS, &c::SLAIRD, 23},
		{"SLA (IR+d),D", a::RELS, &c::SLAIRD, 23},
		{"SLA (IR+d),E", a::RELS, &c::SLAIRD, 23},
		{"SLA (IR+d),H", a::RELS, &c::SLAIRD, 23},
		{"SLA (IR+d),L", a::RELS, &c::SLAIRD, 23},
		{"SLA (IR+d)", a::RELS, &c::SLAIRD, 23},
		{"SLA (IR+d),A", a::RELS, &c::SLAIRD, 23},
		{"SRA (IR+d),B", a::RELS, &c::SRAIRD, 23},
		{"SRA (IR+d),C", a::RELS, &c::SRAIRD, 23},
		{"SRA (IR+d),D", a::RELS, &c::SRAIRD, 23},
		{"SRA (IR+d),E", a::RELS, &c::SRAIRD, 23},
		{"SRA (IR+d),H", a::RELS, &c::SRAIRD, 23},
		{"SRA (IR+d),L", a::RELS, &c::SRAIRD, 23},
		{"SRA (IR+d)", a::RELS, &c::SRAIRD, 23},
		{"SRA (IR+d),A", a::RELS, &c::SRAIRD, 23},
		{"SLS (IR+d),B", a::RELS, &c::SLSIRD, 23},
		{"SLS (IR+d),C", a::RELS, &c::SLSIRD, 23},
		{"SLS (IR+d),D", a::RELS, &c::SLSIRD, 23},
		{"SLS (IR+d),E", a::RELS, &c::SLSIRD, 23},
		{"SLS (IR+d),H", a::RELS, &c::SLSIRD, 23},
		{"SLS (IR+d),L", a::RELS, &c::SLSIRD, 23},
		{"SLS (IR+d)", a::RELS, &c::SLSIRD, 23},
		{"SLS (IR+d),A", a::RELS, &c::SLSIRD, 23},
		{"SRL (IR+d),B", a::RELS, &c::SRLIRD, 23},
		{"SRL (IR+d),C", a::RELS, &c::SRLIRD, 23},
		{"SRL (IR+d),D", a::RELS, &c::SRLIRD, 23},
		{"SRL (IR+d),E", a::RELS, &c::SRLIRD, 23},
		{"SRL (IR+d),H", a::RELS, &c::SRLIRD, 23},
		{"SRL (IR+d),L", a::RELS, &c::SRLIRD, 23},
		{"SRL (IR+d)", a::RELS, &c::SRLIRD, 23},
		{"SRL (IR+d),A", a::RELS, &c::SRLIRD, 23},
		{"BIT 0,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 0,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 0,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 0,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 0,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 0,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 0,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 0,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 1,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 1,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 1,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 1,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 1,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 1,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 1,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 1,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 2,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 2,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 2,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 2,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 2,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 2,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 2,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 2,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 3,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 3,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 3,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 3,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 3,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 3,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 3,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 3,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 4,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 4,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 4,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 4,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 4,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 4,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 4,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 4,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 5,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 5,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 5,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 5,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 5,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 5,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 5,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 5,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 6,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 6,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 6,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 6,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 6,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 6,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 6,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 6,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 7,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 7,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 7,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 7,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 7,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 7,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 7,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"BIT 7,(IR+d)", a::RELS, &c::BITBIRD, 20},
		{"RES 0,(IR+d),B", a::RELS, &c::RESBIRD, 23},
		{"RES 0,(IR+d),C", a::RELS, &c::RESBIRD, 23},
		{"RES 0,(IR+d),D", a::RELS, &c::RESBIRD, 23},
		{"RES 0,(IR+d),E", a::RELS, &c::RESBIRD, 23},
		{"RES 0,(IR+d),H", a::RELS, &c::RESBIRD, 23},
		{"RES 0,(IR+d),L", a::RELS, &c::RESBIRD, 23},
		{"RES 0,(IR+d)", a::RELS, &c::RESBIRD, 23},
		{"RES 0,(IR+d),A", a::RELS, &c::RESBIRD, 23},
		{"RES 1,(IR+d),B", a::RELS, &c::RESBIRD, 23},
		{"RES 1,(IR+d),C", a::RELS, &c::RESBIRD, 23},
		{"RES 1,(IR+d),D", a::RELS, &c::RESBIRD, 23},
		{"RES 1,(IR+d),E", a::RELS, &c::RESBIRD, 23},
		{"RES 1,(IR+d),H", a::RELS, &c::RESBIRD, 23},
		{"RES 1,(IR+d),L", a::RELS, &c::RESBIRD, 23},
		{"RES 1,(IR+d)", a::RELS, &c::RESBIRD, 23},
		{"RES 1,(IR+d),A", a::RELS, &c::RESBIRD, 23},
		{"RES 2,(IR+d),B", a::RELS, &c::RESBIRD, 23},
		{"RES 2,(IR+d),C", a::RELS, &c::RESBIRD, 23},
		{"RES 2,(IR+d),D", a::RELS, &c::RESBIRD, 23},
		{"RES 2,(IR+d),E", a::RELS, &c::RESBIRD, 23},
		{"RES 2,(IR+d),H", a::RELS, &c::RESBIRD, 23},
		{"RES 2,(IR+d),L", a::RELS, &c::RESBIRD, 23},
		{"RES 2,(IR+d)", a::RELS, &c::RESBIRD, 23},
		{"RES 2,(IR+d),A", a::RELS, &c::RESBIRD, 23},
		{"RES 3,(IR+d),B", a::RELS, &c::RESBIRD, 23},
		{"RES 3,(IR+d),C", a::RELS, &c::RESBIRD, 23},
		{"RES 3,(IR+d),D", a::RELS, &c::RESBIRD, 23},
		{"RES 3,(IR+d),E", a::RELS, &c::RESBIRD, 23},
		{"RES 3,(IR+d),H", a::RELS, &c::RESBIRD, 23},
		{"RES 3,(IR+d),L", a::RELS, &c::RESBIRD, 23},
		{"RES 3,(IR+d)", a::RELS, &c::RESBIRD, 23},
		{"RES 3,(IR+d),A", a::RELS, &c::RESBIRD, 23},
		{"RES 4,(IR+d),B", a::RELS, &c::RESBIRD, 23},
		{"RES 4,(IR+d),C", a::RELS, &c::RESBIRD, 23},
		{"RES 4,(IR+d),D", a::RELS, &c::RESBIRD, 23},
		{"RES 4,(IR+d),E", a::RELS, &c::RESBIRD, 23},
		{"RES 4,(IR+d),H", a::RELS, &c::RESBIRD, 23},
		{"RES 4,(IR+d),L", a::RELS, &c::RESBIRD, 23},
		{"RES 4,(IR+d)", a::RELS, &c::RESBIRD, 23},
		{"RES 4,(IR+d),A", a::RELS, &c::RESBIRD, 23},
		{"RES 5,(IR+d),B", a::RELS, &c::RESBIRD, 23},
		{"RES 5,(IR+d),C", a::RELS, &c::RESBIRD, 23},
		{"RES 5,(IR+d),D", a::RELS, &c::RESBIRD, 23},
		{"RES 5,(IR+d),E", a::RELS, &c::RESBIRD, 23},
		{"RES 5,(IR+d),H", a::RELS, &c::RESBIRD, 23},
		{"RES 5,(IR+d),L", a::RELS, &c::RESBIRD, 23},
		{"RES 5,(IR+d)", a::RELS, &c::RESBIRD, 23},
		{"RES 5,(IR+d),A", a::RELS, &c::RESBIRD, 23},
		{"RES 6,(IR+d),B", a::RELS, &c::RESBIRD, 23},
		{"RES 6,(IR+d),C", a::RELS, &c::RESBIRD, 23},
		{"RES 6,(IR+d),D", a::RELS, &c::RESBIRD, 23},
		{"RES 6,(IR+d),E", a::RELS, &c::RESBIRD, 23},
		{"RES 6,(IR+d),H", a::RELS, &c::RESBIRD, 23},
		{"RES 6,(IR+d),L", a::RELS, &c::RESBIRD, 23},
		{"RES 6,(IR+d)", a::RELS, &c::RESBIRD, 23},
		{"RES 6,(IR+d),A", a::RELS, &c::RESBIRD, 23},
		{"RES 7,(IR+d),B", a::RELS, &c::RESBIRD, 23},
		{"RES 7,(IR+d),C", a::RELS, &c::RESBIRD, 23},
		{"RES 7,(IR+d),D", a::RELS, &c::RESBIRD, 23},
		{"RES 7,(IR+d),E", a::RELS, &c::RESBIRD, 23},
		{"RES 7,(IR+d),H", a::RELS, &c::RESBIRD, 23},
		{"RES 7,(IR+d),L", a::RELS, &c::RESBIRD, 23},
		{"RES 7,(IR+d)", a::RELS, &c::RESBIRD, 23},
		{"RES 7,(IR+d),A", a::RELS, &c::RESBIRD, 23},
		{"SET 0,(IR+d),B", a::RELS, &c::SETBIRD, 23},
		{"SET 0,(IR+d),C", a::RELS, &c::SETBIRD, 23},
		{"SET 0,(IR+d),D", a::RELS, &c::SETBIRD, 23},
		{"SET 0,(IR+d),E", a::RELS, &c::SETBIRD, 23},
		{"SET 0,(IR+d),H", a::RELS, &c::SETBIRD, 23},
		{"SET 0,(IR+d),L", a::RELS, &c::SETBIRD, 23},
		{"SET 0,(IR+d)", a::RELS, &c::SETBIRD, 23},
		{"SET 0,(IR+d),A", a::RELS, &c::SETBIRD, 23},
		{"SET 1,(IR+d),B", a::RELS, &c::SETBIRD, 23},
		{"SET 1,(IR+d),C", a::RELS, &c::SETBIRD, 23},
		{"SET 1,(IR+d),D", a::RELS, &c::SETBIRD, 23},
		{"SET 1,(IR+d),E", a::RELS, &c::SETBIRD, 23},
		{"SET 1,(IR+d),H", a::RELS, &c::SETBIRD, 23},
		{"SET 1,(IR+d),L", a::RELS, &c::SETBIRD, 23},
		{"SET 1,(IR+d)", a::RELS, &c::SETBIRD, 23},
		{"SET 1,(IR+d),A", a::RELS, &c::SETBIRD, 23},
		{"SET 2,(IR+d),B", a::RELS, &c::SETBIRD, 23},
		{"SET 2,(IR+d),C", a::RELS, &c::SETBIRD, 23},
		{"SET 2,(IR+d),D", a::RELS, &c::SETBIRD, 23},
		{"SET 2,(IR+d),E", a::RELS, &c::SETBIRD, 23},
		{"SET 2,(IR+d),H", a::RELS, &c::SETBIRD, 23},
		{"SET 2,(IR+d),L", a::RELS, &c::SETBIRD, 23},
		{"SET 2,(IR+d)", a::RELS, &c::SETBIRD, 23},
		{"SET 2,(IR+d),A", a::RELS, &c::SETBIRD, 23},
		{"SET 3,(IR+d),B", a::RELS, &c::SETBIRD, 23},
		{"SET 3,(IR+d),C", a::RELS, &c::SETBIRD, 23},
		{"SET 3,(IR+d),D", a::RELS, &c::SETBIRD, 23},
		{"SET 3,(IR+d),E", a::RELS, &c::SETBIRD, 23},
		{"SET 3,(IR+d),H", a::RELS, &c::SETBIRD, 23},
		{"SET 3,(IR+d),L", a::RELS, &c::SETBIRD, 23},
		{"SET 3,(IR+d)", a::RELS, &c::SETBIRD, 23},
		{"SET 3,(IR+d),A", a::RELS, &c::SETBIRD, 23},
		{"SET 4,(IR+d),B", a::RELS, &c::SETBIRD, 23},
		{"SET 4,(IR+d),C", a::RELS, &c::SETBIRD, 23},
		{"SET 4,(IR+d),D", a::RELS, &c::SETBIRD, 23},
		{"SET 4,(IR+d),E", a::RELS, &c::SETBIRD, 23},
		{"SET 4,(IR+d),H", a::RELS, &c::SETBIRD, 23},
		{"SET 4,(IR+d),L", a::RELS, &c::SETBIRD, 23},
		{"SET 4,(IR+d)", a::RELS, &c::SETBIRD, 23},
		{"SET 4,(IR+d),A", a::RELS, &c::SETBIRD, 23},
		{"SET 5,(IR+d),B", a::RELS, &c::SETBIRD, 23},
		{"SET 5,(IR+d),C", a::RELS, &c::SETBIRD, 23},
		{"SET 5,(IR+d),D", a::RELS, &c::SETBIRD, 23},
		{"SET 5,(IR+d),E", a::RELS, &c::SETBIRD, 23},
		{"SET 5,(IR+d),H", a::RELS, &c::SETBIRD, 23},
		{"SET 5,(IR+d),L", a::RELS, &c::SETBIRD, 23},
		{"SET 5,(IR+d)", a::RELS, &c::SETBIRD, 23},
		{"SET 5,(IR+d),A", a::RELS, &c::SETBIRD, 23},
		{"SET 6,(IR+d),B", a::RELS, &c::SETBIRD, 23},
		{"SET 6,(IR+d),C", a::RELS, &c::SETBIRD, 23},
		{"SET 6,(IR+d),D", a::RELS, &c::SETBIRD, 23},
		{"SET 6,(IR+d),E", a::RELS, &c::SETBIRD, 23},
		{"SET 6,(IR+d),H", a::RELS, &c::SETBIRD, 23},
		{"SET 6,(IR+d),L", a::RELS, &c::SETBIRD, 23},
		{"SET 6,(IR+d)", a::RELS, &c::SETBIRD, 23},
		{"SET 6,(IR+d),A", a::RELS, &c::SETBIRD, 23},
		{"SET 7,(IR+d),B", a::RELS, &c::SETBIRD, 23},
		{"SET 7,(IR+d),C", a::RELS, &c::SETBIRD, 23},
		{"SET 7,(IR+d),D", a::RELS, &c::SETBIRD, 23},
		{"SET 7,(IR+d),E", a::RELS, &c::SETBIRD, 23},
		{"SET 7,(IR+d),H", a::RELS, &c::SETBIRD, 23},
		{"SET 7,(IR+d),L", a::RELS, &c::SETBIRD, 23},
		{"SET 7,(IR+d)", a::RELS, &c::SETBIRD, 23},
		{"SET 7,(IR+d),A", a::RELS, &c::SETBIRD, 23},
	};

}
