#include "Z80.h"

void Z80::initInstructions()
{
	using c = Z80;
	using a = AddressingModes;

	rootInstructions =
	{
		{"NOP", a::IMP, &c::NOP, 4},
		{"LD BC,nn", a::IMX, &c::LDDDNN, 10},
		{"LD (BC),A", a::IMP, &c::LDBCA, 7},
		{"INC BC", a::IMP, &c::INCSS, 6},
		{"INC B", a::IMP, &c::INCR, 4},
		{"DEC B", a::IMP, &c::DECR, 4},
		{"LD B,n", a::IMM, &c::LDRN, 7},
		{"RLCA", a::IMP, &c::RLCA, 4},
		{"EX AF,AF'", a::IMP, &c::EXAFAF, 4},
		{"ADD HL,BC", a::IMP, &c::ADDHLSS, 11},
		{"LD A,(BC)", a::IDX, &c::LDABC, 7},
		{"DEC BC", a::IMP, &c::DECSS, 6},
		{"INC C", a::IMP, &c::INCR, 4},
		{"DEC C", a::IMP, &c::DECR, 4},
		{"LD C,n", a::IMM, &c::LDRN, 7},
		{"RRCA", a::IMP, &c::RRCA, 4},
		{"DJNZ e", a::REL, &c::DJNZE, 8},
		{"LD DE,nn", a::IMX, &c::LDDDNN, 10},
		{"LD (DE),A", a::IMP, &c::LDDEA, 7},
		{"INC DE", a::IMP, &c::INCSS, 6},
		{"INC D", a::IMP, &c::INCR, 4},
		{"DEC D", a::IMP, &c::DECR, 4},
		{"LD D,n", a::IMM, &c::LDRN, 7},
		{"RLA", a::IMP, &c::RLA, 4},
		{"JR e", a::REL, &c::JRE, 12},
		{"ADD HL,DE", a::IMP, &c::ADDHLSS, 11},
		{"LD A,(DE)", a::IDX, &c::LDADE, 7},
		{"DEC DE", a::IMP, &c::DECSS, 6},
		{"INC E", a::IMP, &c::INCR, 4},
		{"DEC E", a::IMP, &c::DECR, 4},
		{"LD E,n", a::IMM, &c::LDRN, 7},
		{"RRA", a::IMP, &c::RRA, 4},
		{"JR NZ,e", a::REL, &c::JRNZE, 7},
		{"LD HL,nn", a::IMX, &c::LDDDNN, 10},
		{"LD (nn),HL", a::IMX, &c::LDNNHL, 16},
		{"INC HL", a::IMP, &c::INCSS, 6},
		{"INC H", a::IMP, &c::INCR, 4},
		{"DEC H", a::IMP, &c::DECR, 4},
		{"LD H,n", a::IMM, &c::LDRN, 7},
		{"DAA", a::IMP, &c::DAA, 4},
		{"JR Z,e", a::REL, &c::JRZE, 7},
		{"ADD HL,HL", a::IMP, &c::ADDHLSS, 11},
		{"LD HL,(nn)", a::IMX, &c::LDHLNN, 16},
		{"DEC HL", a::IMP, &c::DECSS, 6},
		{"INC L", a::IMP, &c::INCR, 4},
		{"DEC L", a::IMP, &c::DECR, 4},
		{"LD L,n", a::IMM, &c::LDRN, 7},
		{"CPL", a::IMP, &c::CPL, 4},
		{"JR NC,e", a::REL, &c::JRNCE, 7},
		{"LD SP,nn", a::IMX, &c::LDDDNN, 10},
		{"LD (nn),A", a::IMX, &c::LDNNA, 13},
		{"INC SP", a::IMP, &c::INCSS, 6},
		{"INC (HL)", a::RGIHL, &c::INCHL, 11},
		{"DEC (HL)", a::RGIHL, &c::DECHL, 11},
		{"LD (HL),n", a::IMM, &c::LDHLN, 10},
		{"SCF", a::IMP, &c::SCF, 4},
		{"JR C,e", a::REL, &c::JRCE, 7},
		{"ADD HL,SP", a::IMP, &c::ADDHLSS, 11},
		{"LD A,(nn)", a::IMX, &c::LDANN, 13},
		{"DEC SP", a::IMP, &c::DECSS, 6},
		{"INC A", a::IMP, &c::INCR, 4},
		{"DEC A", a::IMP, &c::DECR, 4},
		{"LD A,n", a::IMM, &c::LDRN, 7},
		{"CCF", a::IMP, &c::CCF, 4},
		{"LD B,B", a::REG, &c::LDRR, 4},
		{"LD B,C", a::REG, &c::LDRR, 4},
		{"LD B,D", a::REG, &c::LDRR, 4},
		{"LD B,E", a::REG, &c::LDRR, 4},
		{"LD B,H", a::REG, &c::LDRR, 4},
		{"LD B,L", a::REG, &c::LDRR, 4},
		{"LD B,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD B,A", a::REG, &c::LDRR, 4},
		{"LD C,B", a::REG, &c::LDRR, 4},
		{"LD C,C", a::REG, &c::LDRR, 4},
		{"LD C,D", a::REG, &c::LDRR, 4},
		{"LD C,E", a::REG, &c::LDRR, 4},
		{"LD C,H", a::REG, &c::LDRR, 4},
		{"LD C,L", a::REG, &c::LDRR, 4},
		{"LD C,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD C,A", a::REG, &c::LDRR, 4},
		{"LD D,B", a::REG, &c::LDRR, 4},
		{"LD D,C", a::REG, &c::LDRR, 4},
		{"LD D,D", a::REG, &c::LDRR, 4},
		{"LD D,E", a::REG, &c::LDRR, 4},
		{"LD D,H", a::REG, &c::LDRR, 4},
		{"LD D,L", a::REG, &c::LDRR, 4},
		{"LD D,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD D,A", a::REG, &c::LDRR, 4},
		{"LD E,B", a::REG, &c::LDRR, 4},
		{"LD E,C", a::REG, &c::LDRR, 4},
		{"LD E,D", a::REG, &c::LDRR, 4},
		{"LD E,E", a::REG, &c::LDRR, 4},
		{"LD E,H", a::REG, &c::LDRR, 4},
		{"LD E,L", a::REG, &c::LDRR, 4},
		{"LD E,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD E,A", a::REG, &c::LDRR, 4},
		{"LD H,B", a::REG, &c::LDRR, 4},
		{"LD H,C", a::REG, &c::LDRR, 4},
		{"LD H,D", a::REG, &c::LDRR, 4},
		{"LD H,E", a::REG, &c::LDRR, 4},
		{"LD H,H", a::REG, &c::LDRR, 4},
		{"LD H,L", a::REG, &c::LDRR, 4},
		{"LD H,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD H,A", a::REG, &c::LDRR, 4},
		{"LD L,B", a::REG, &c::LDRR, 4},
		{"LD L,C", a::REG, &c::LDRR, 4},
		{"LD L,D", a::REG, &c::LDRR, 4},
		{"LD L,E", a::REG, &c::LDRR, 4},
		{"LD L,H", a::REG, &c::LDRR, 4},
		{"LD L,L", a::REG, &c::LDRR, 4},
		{"LD L,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD L,A", a::REG, &c::LDRR, 4},
		{"LD (HL),B", a::IMP, &c::LDHLR, 7},
		{"LD (HL),C", a::IMP, &c::LDHLR, 7},
		{"LD (HL),D", a::IMP, &c::LDHLR, 7},
		{"LD (HL),E", a::IMP, &c::LDHLR, 7},
		{"LD (HL),H", a::IMP, &c::LDHLR, 7},
		{"LD (HL),L", a::IMP, &c::LDHLR, 7},
		{"HALT", a::IMP, &c::HALT, 4},
		{"LD (HL),A", a::IMP, &c::LDHLR, 7},
		{"LD A,B", a::REG, &c::LDRR, 4},
		{"LD A,C", a::REG, &c::LDRR, 4},
		{"LD A,D", a::REG, &c::LDRR, 4},
		{"LD A,E", a::REG, &c::LDRR, 4},
		{"LD A,H", a::REG, &c::LDRR, 4},
		{"LD A,L", a::REG, &c::LDRR, 4},
		{"LD A,(HL)", a::RGIHL, &c::LDRHL, 7},
		{"LD A,A", a::REG, &c::LDRR, 4},
		{"ADD A,B", a::REG, &c::ADDAR, 4},
		{"ADD A,C", a::REG, &c::ADDAR, 4},
		{"ADD A,D", a::REG, &c::ADDAR, 4},
		{"ADD A,E", a::REG, &c::ADDAR, 4},
		{"ADD A,H", a::REG, &c::ADDAR, 4},
		{"ADD A,L", a::REG, &c::ADDAR, 4},
		{"ADD A,(HL)", a::RGIHL, &c::ADDAHL, 7},
		{"ADD A,A", a::REG, &c::ADDAR, 4},
		{"ADC A,B", a::REG, &c::ADCAR, 4},
		{"ADC A,C", a::REG, &c::ADCAR, 4},
		{"ADC A,D", a::REG, &c::ADCAR, 4},
		{"ADC A,E", a::REG, &c::ADCAR, 4},
		{"ADC A,H", a::REG, &c::ADCAR, 4},
		{"ADC A,L", a::REG, &c::ADCAR, 4},
		{"ADC A,(HL)", a::RGIHL, &c::ADCAHL, 7},
		{"ADC A,A", a::REG, &c::ADCAR, 4},
		{"SUB A,B", a::REG, &c::SUBR, 4},
		{"SUB A,C", a::REG, &c::SUBR, 4},
		{"SUB A,D", a::REG, &c::SUBR, 4},
		{"SUB A,E", a::REG, &c::SUBR, 4},
		{"SUB A,H", a::REG, &c::SUBR, 4},
		{"SUB A,L", a::REG, &c::SUBR, 4},
		{"SUB A,(HL)", a::RGIHL, &c::SUBHL, 7},
		{"SUB A,A", a::REG, &c::SUBR, 4},
		{"SBC A,B", a::REG, &c::SBCAR, 4},
		{"SBC A,C", a::REG, &c::SBCAR, 4},
		{"SBC A,D", a::REG, &c::SBCAR, 4},
		{"SBC A,E", a::REG, &c::SBCAR, 4},
		{"SBC A,H", a::REG, &c::SBCAR, 4},
		{"SBC A,L", a::REG, &c::SBCAR, 4},
		{"SBC A,(HL)", a::RGIHL, &c::SBCAHL, 7},
		{"SBC A,A", a::REG, &c::SBCAR, 4},
		{"AND B", a::IMP, &c::ANDR, 4},
		{"AND C", a::IMP, &c::ANDR, 4},
		{"AND D", a::IMP, &c::ANDR, 4},
		{"AND E", a::IMP, &c::ANDR, 4},
		{"AND H", a::IMP, &c::ANDR, 4},
		{"AND L", a::IMP, &c::ANDR, 4},
		{"AND (HL)", a::RGIHL, &c::ANDHL, 7},
		{"AND A", a::IMP, &c::ANDR, 4},
		{"XOR B", a::IMP, &c::XORR, 4},
		{"XOR C", a::IMP, &c::XORR, 4},
		{"XOR D", a::IMP, &c::XORR, 4},
		{"XOR E", a::IMP, &c::XORR, 4},
		{"XOR H", a::IMP, &c::XORR, 4},
		{"XOR L", a::IMP, &c::XORR, 4},
		{"XOR (HL)", a::RGIHL, &c::XORHL, 7},
		{"XOR A", a::IMP, &c::XORR, 4},
		{"OR B", a::IMP, &c::ORR, 4},
		{"OR C", a::IMP, &c::ORR, 4},
		{"OR D", a::IMP, &c::ORR, 4},
		{"OR E", a::IMP, &c::ORR, 4},
		{"OR H", a::IMP, &c::ORR, 4},
		{"OR L", a::IMP, &c::ORR, 4},
		{"OR (HL)", a::RGIHL, &c::ORHL, 7},
		{"OR A", a::IMP, &c::ORR, 4},
		{"CP B", a::IMP, &c::CPR, 4},
		{"CP C", a::IMP, &c::CPR, 4},
		{"CP D", a::IMP, &c::CPR, 4},
		{"CP E", a::IMP, &c::CPR, 4},
		{"CP H", a::IMP, &c::CPR, 4},
		{"CP L", a::IMP, &c::CPR, 4},
		{"BP (HL)", a::RGIHL, &c::CPHL, 7},
		{"CP A", a::IMP, &c::CPR, 4},
		{"RET NZ", a::IMP, &c::RETCC, 5},
		{"POP BC", a::IMP, &c::POPQQ, 10},
		{"JP NZ,nn", a::IMX, &c::JPCCNN, 10},
		{"JP nn", a::IMX, &c::JPNN, 10},
		{"CALL NZ,nn", a::IMX, &c::CALLCCNN, 10},
		{"PUSH BC", a::IMP, &c::PUSHQQ, 11},
		{"ADD A,n", a::IMM, &c::ADDAN, 7},
		{"RST &00", a::IMP, &c::RSTP, 11},
		{"RET Z", a::IMP, &c::RETCC, 5},
		{"RET", a::IMP, &c::RET, 10},
		{"JP Z,nn", a::IMX, &c::JPCCNN, 10},
		{"???", a::IMP, &c::XXX, 4},
		{"CALL Z,nn", a::IMX, &c::CALLCCNN, 10},
		{"CALL nn", a::IMX, &c::CALLNN, 17},
		{"ADC A,n", a::IMM, &c::ADCAN, 7},
		{"RST &08", a::IMP, &c::RSTP, 11},
		{"RET NC", a::IMP, &c::RETCC, 5},
		{"POP DE", a::IMP, &c::POPQQ, 10},
		{"JP NC,nn", a::IMX, &c::JPCCNN, 10},
		{"OUT (n),A", a::IMM, &c::OUTNA, 11},
		{"CALL NC,nn", a::IMX, &c::CALLCCNN, 10},
		{"PUSH DE", a::IMP, &c::PUSHQQ, 11},
		{"SUB A,n", a::IMM, &c::SUBN, 7},
		{"RST &10", a::IMP, &c::RSTP, 11},
		{"RET Z", a::IMP, &c::RETCC, 5},
		{"EXX", a::IMP, &c::EXX, 4},
		{"JP C,nn", a::IMX, &c::JPCCNN, 10},
		{"IN A,(n)", a::IMM, &c::INAN, 11},
		{"CALL C,nn", a::IMX, &c::CALLCCNN, 10},
		{"???", a::IMP, &c::XXX, 4},
		{"SBC A,n", a::IMM, &c::SBCAN, 7},
		{"RST &18", a::IMP, &c::RSTP, 11},
		{"RET PO", a::IMP, &c::RETCC, 5},
		{"POP HL", a::IMP, &c::POPQQ, 10},
		{"JP PO,nn", a::IMX, &c::JPCCNN, 10},
		{"EX (SP),HL", a::IMP, &c::EXSPHL, 19},
		{"CALL PO,nn", a::IMX, &c::CALLCCNN, 10},
		{"PUSH HL", a::IMP, &c::PUSHQQ, 11},
		{"AND n", a::IMM, &c::ANDN, 7},
		{"RST &20", a::IMP, &c::RSTP, 11},
		{"RET PE", a::IMP, &c::RETCC, 5},
		{"JP (HL)", a::IMP, &c::JPHL, 4},
		{"JP PE,nn", a::IMX, &c::JPCCNN, 10},
		{"EX DE,HL", a::IMP, &c::EXDEHL, 4},
		{"CALL PE,nn", a::IMX, &c::CALLCCNN, 10},
		{"???", a::IMP, &c::XXX, 4},
		{"XOR n", a::IMM, &c::XORN, 7},
		{"RST &28", a::IMP, &c::RSTP, 11},
		{"RET P", a::IMP, &c::RETCC, 5},
		{"POP AF", a::IMP, &c::POPQQ, 10},
		{"JP P,nn", a::IMX, &c::JPCCNN, 10},
		{"DI", a::IMP, &c::DI, 4},
		{"CALL P,nn", a::IMX, &c::CALLCCNN, 10},
		{"PUSH AF", a::IMP, &c::PUSHQQ, 11},
		{"OR n", a::IMM, &c::ORN, 7},
		{"RST &30", a::IMP, &c::RSTP, 11},
		{"RET M", a::IMP, &c::RETCC, 5},
		{"LD SP,HL", a::IMP, &c::LDSPHL, 6},
		{"JP M,nn",a::IMX, &c::JPCCNN, 10},
		{"EI", a::IMP, &c::EI, 4},
		{"CALL M,nn", a::IMX, &c::CALLCCNN, 10},
		{ "???", a::IMP, &c::XXX, 4 },
		{"CP n", a::IMM, &c::CPN, 7},
		{"RST &38", a::IMP, &c::RSTP, 11},
	};

	ddInstructions =
	{
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IX,BC", a::IMP, &c::ADDIXPP, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IX,DE", a::IMP, &c::ADDIXPP, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD IX,nn", a::IMX, &c::LDIXNN, 14},
		{"LD (nn),IX", a::IMX, &c::LDNNIX, 20},
		{"INC IX", a::IMP, &c::INCIX, 10},
		{"INC IXh", a::IMP, &c::INCIXH, 8},
		{"DEC IXh", a::IMP, &c::DECIXH, 8},
		{"LD IXh,n", a::IMM, &c::LDIXHN, 11},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IX,IX", a::IMP, &c::ADDIXPP, 15},
		{"LD IX,(nn)", a::IMX, &c::LDIXFNN, 20},
		{"DEC IX", a::IMP, &c::DECIX, 10},
		{"INC IXl", a::IMP, &c::INCIXL, 8},
		{"DEC IXl", a::IMP, &c::DECIXL, 8},
		{"LD IXl,n", a::IMM, &c::LDIXLN, 11},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"INC (IX+d)", a::REL, &c::INCIXD, 23},
		{"DEC (IX+d)", a::REL, &c::DECIXD, 23},
		{"LD (IX+d),n", a::REL, &c::LDIXDN, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IX,SP", a::IMP, &c::ADDIXPP, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD B,IXh", a::IMP, &c::LDRIXH, 8},
		{"LD B,IXl", a::IMP, &c::LDRIXL, 8},
		{"LD B,(IX+d)", a::REL, &c::LDRIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD C,IXh", a::IMP, &c::LDRIXH, 8},
		{"LD C,IXl", a::IMP, &c::LDRIXL, 8},
		{"LD C,(IX+d)", a::REL, &c::LDRIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD D,IXh", a::IMP, &c::LDRIXH, 8},
		{"LD D,IXl", a::IMP, &c::LDRIXL, 8},
		{"LD D,(IX+d)", a::REL, &c::LDRIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD E,IXh", a::IMP, &c::LDRIXH, 8},
		{"LD E,IXl", a::IMP, &c::LDRIXL, 8},
		{"LD E,(IX+d)", a::REL, &c::LDRIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"LD IXh,B", a::IMP, &c::LDIXHR, 8},
		{"LD IXh,C", a::IMP, &c::LDIXHR, 8},
		{"LD IXh,D", a::IMP, &c::LDIXHR, 8},
		{"LD IXh,E", a::IMP, &c::LDIXHR, 8},
		{"LD IXh,IXh", a::IMP, &c::LDIXHIXH, 8},
		{"LD IXh,IXl", a::IMP, &c::LDIXHIXL, 8},
		{"LD H,(IX+d)", a::REL, &c::LDRIXD, 19},
		{"LD IXh,A", a::IMP, &c::LDIXHR, 8},
		{"LD IXl,B", a::IMP, &c::LDIXLR, 8},
		{"LD IXl,C", a::IMP, &c::LDIXLR, 8},
		{"LD IXl,D", a::IMP, &c::LDIXLR, 8},
		{"LD IXl,E", a::IMP, &c::LDIXLR, 8},
		{"LD IXl,IXh", a::IMP, &c::LDIXLIXH, 8},
		{"LD IXl,IXl", a::IMP, &c::LDIXLIXL, 8},
		{"LD L,(IX+d)", a::REL, &c::LDRIXD, 19},
		{"LD IXl,A", a::IMP, &c::LDIXLR, 8},
		{"LD (IX+d),B", a::REL, &c::LDIXDR, 19},
		{"LD (IX+d),C", a::REL, &c::LDIXDR, 19},
		{"LD (IX+d),D", a::REL, &c::LDIXDR, 19},
		{"LD (IX+d),E", a::REL, &c::LDIXDR, 19},
		{"LD (IX+d),H", a::REL, &c::LDIXDR, 19},
		{"LD (IX+d),L", a::REL, &c::LDIXDR, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"LD (IX+d),A", a::REL, &c::LDIXDR, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD A,IXh", a::IMP, &c::LDRIXH, 8},
		{"LD A,IXl", a::IMP, &c::LDRIXL, 8},
		{"LD A,(IX+d)", a::REL, &c::LDRIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD A,IXH", a::IMP, &c::ADDAIXH, 8},
		{"ADD A,IXL", a::IMP, &c::ADDAIXL, 8},
		{"ADD A,(IX+d)", a::REL, &c::ADDAIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADC A,IXH", a::IMP, &c::ADCAIXH, 8},
		{"ADC A,IXL", a::IMP, &c::ADCAIXL, 8},
		{"ADC A,(IX+d)", a::REL, &c::ADCAIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"SUB A,IXH", a::IMP, &c::SUBAIXH, 8},
		{"SUB A,IXL", a::IMP, &c::SUBAIXL, 8},
		{"SUB A,(IX+d)", a::REL, &c::SUBIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"SBC A,IXH", a::IMP, &c::SBCAIXH, 8},
		{"SBC A,IXL", a::IMP, &c::SBCAIXL, 8},
		{"SBC A,(IX+d)", a::REL, &c::SBCAIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"AND IXH", a::IMP, &c::ANDIXH, 8},
		{"AND IXL", a::IMP, &c::ANDIXL, 8},
		{"AND (IX+d)", a::REL, &c::ANDIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"XOR IXH", a::IMP, &c::XORIXH, 8},
		{"XOR IXL", a::IMP, &c::XORIXL, 8},
		{"XOR (IX+d)", a::REL, &c::XORIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"OR IXH", a::IMP, &c::ORIXH, 8},
		{"OR IXL", a::IMP, &c::ORIXL, 8},
		{"OR (IX+d)", a::REL, &c::ORIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"CP IXH", a::IMP, &c::CPIXH, 8},
		{"CP IXL", a::IMP, &c::CPIXL, 8},
		{"CP (IX+d)", a::REL, &c::CPIXD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"POP IX", a::IMP, &c::POPIX, 14},
		{"???", a::IMP, &c::XXX, 4},
		{"EX (SP),IX", a::IMP, &c::EXSPIX, 23},
		{"???", a::IMP, &c::XXX, 4},
		{"PUSH IX", a::IMP, &c::PUSHIX, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"JP (IX)", a::IMP, &c::JPIX, 8},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD SP,IX", a::IMP, &c::LDSPIX, 10},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
	};

	fdInstructions =
	{
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IY,BC", a::IMP, &c::ADDIYRR, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IY,DE", a::IMP, &c::ADDIYRR, 15},
		{"LD IY,nn", a::IMX, &c::LDIYNN, 14},
		{"LD (nn),IY", a::IMX, &c::LDNNIY, 20},
		{"INC IY", a::IMP, &c::INCIY, 10},
		{"INC IYh", a::IMP, &c::INCIYH, 8},
		{"DEC IYh", a::IMP, &c::DECIYH, 8},
		{"LD IYh,n", a::IMM, &c::LDIYHN, 11},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IY,IY", a::IMP, &c::ADDIYRR, 15},
		{"LD IY,(nn)", a::IMX, &c::LDIYFNN, 20},
		{"DEC IY", a::IMP, &c::DECIY, 10},
		{"INC IYl", a::IMP, &c::INCIYL, 8},
		{"DEC IYl", a::IMP, &c::DECIYL, 8},
		{"LD IYl,n", a::IMM, &c::LDIYLN, 11},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"INC (IY+d)", a::REL, &c::INCIYD, 23},
		{"DEC (IY+d)", a::REL, &c::DECIYD, 23},
		{"LD (IY+d),n", a::REL, &c::LDIYDN, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD IY,SP", a::IMP, &c::ADDIYRR, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD B,IYh", a::IMP, &c::LDRIYH, 8},
		{"LD B,IYl", a::IMP, &c::LDRIYL, 8},
		{"LD B,(IY+d)", a::REL, &c::LDRIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD C,IYh", a::IMP, &c::LDRIYH, 8},
		{"LD C,IYl", a::IMP, &c::LDRIYL, 8},
		{"LD C,(IY+d)", a::REL, &c::LDRIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD D,IYh", a::IMP, &c::LDRIYH, 8},
		{"LD D,IYl", a::IMP, &c::LDRIYL, 8},
		{"LD D,(IY+d)", a::REL, &c::LDRIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD E,IYh", a::IMP, &c::LDRIYH, 8},
		{"LD E,IYl", a::IMP, &c::LDRIYL, 8},
		{"LD E,(IY+d)", a::REL, &c::LDRIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"LD IYh,B", a::IMP, &c::LDIYHR, 8},
		{"LD IYh,C", a::IMP, &c::LDIYHR, 8},
		{"LD IYh,D", a::IMP, &c::LDIYHR, 8},
		{"LD IYh,E", a::IMP, &c::LDIYHR, 8},
		{"LD IYh,IYh", a::IMP, &c::LDIYHIYH, 8},
		{"LD IYh,IYl", a::IMP, &c::LDIYHIYL, 8},
		{"LD H,(IY+d)", a::REL, &c::LDRIYD, 19},
		{"LD IYh,A", a::IMP, &c::LDIYHR, 8},
		{"LD IYl,B", a::IMP, &c::LDIYLR, 8},
		{"LD IYl,C", a::IMP, &c::LDIYLR, 8},
		{"LD IYl,D", a::IMP, &c::LDIYLR, 8},
		{"LD IYl,E", a::IMP, &c::LDIYLR, 8},
		{"LD IYl,IYh", a::IMP, &c::LDIYLIYH, 8},
		{"LD IYl,IYl", a::IMP, &c::LDIYLIYL, 8},
		{"LD L,(IY+d)", a::REL, &c::LDRIYD, 19},
		{"LD IYl,A", a::IMP, &c::LDIYLR, 8},
		{"LD (IY+d),B", a::REL, &c::LDIYDR, 19},
		{"LD (IY+d),C", a::REL, &c::LDIYDR, 19},
		{"LD (IY+d),D", a::REL, &c::LDIYDR, 19},
		{"LD (IY+d),E", a::REL, &c::LDIYDR, 19},
		{"LD (IY+d),H", a::REL, &c::LDIYDR, 19},
		{"LD (IY+d),L", a::REL, &c::LDIYDR, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"LD (IY+d),A", a::REL, &c::LDIYDR, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD A,IYh", a::IMP, &c::LDRIYH, 8},
		{"LD A,IYl", a::IMP, &c::LDRIYL, 8},
		{"LD A,(IY+d)", a::REL, &c::LDRIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADD A,IYH", a::IMP, &c::ADDAIYH, 8},
		{"ADD A,IYL", a::IMP, &c::ADDAIYL, 8},
		{"ADD A,(IY+d)", a::REL, &c::ADDAIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"ADC A,IYH", a::IMP, &c::ADCAIYH, 8},
		{"ADC A,IYL", a::IMP, &c::ADCAIYL, 8},
		{"ADC A,(IY+d)", a::REL, &c::ADCAIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"SUB A,IYH", a::IMP, &c::SUBAIYH, 8},
		{"SUB A,IYL", a::IMP, &c::SUBAIYL, 8},
		{"SUB A,(IY+d)", a::REL, &c::SUBIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"SBC A,IYH", a::IMP, &c::SBCAIYH, 8},
		{"SBC A,IYL", a::IMP, &c::SBCAIYL, 8},
		{"SBC A,(IY+d)", a::REL, &c::SBCAIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"AND IYH", a::IMP, &c::ANDIYH, 8},
		{"AND IYL", a::IMP, &c::ANDIYL, 8},
		{"AND (IY+d)", a::REL, &c::ANDIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"XOR IYH", a::IMP, &c::XORIYH, 8},
		{"XOR IYL", a::IMP, &c::XORIYL, 8},
		{"XOR (IY+d)", a::REL, &c::XORIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"OR IYH", a::IMP, &c::ORIYH, 8},
		{"OR IYL", a::IMP, &c::ORIYL, 8},
		{"OR (IY+d)", a::REL, &c::ORIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"CP IYH", a::IMP, &c::CPIYH, 8},
		{"CP IYL", a::IMP, &c::CPIYL, 8},
		{"CP (IY+d)", a::REL, &c::CPIYD, 19},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"POP IY", a::IMP, &c::POPIY, 14},
		{"???", a::IMP, &c::XXX, 4},
		{"EX (SP),IY", a::IMP, &c::EXSPIY, 23},
		{"???", a::IMP, &c::XXX, 4},
		{"PUSH IY", a::IMP, &c::PUSHIY, 15},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"JP (IY)", a::IMP, &c::JPIY, 8},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LD SP,IY", a::IMP, &c::LDSPIY, 10},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
	};

	edInstructions =
	{
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"IN B,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),B", a::IMP, &c::OUTCR, 12},
		{"SBC HL,BC", a::IMP, &c::SBCHLSS, 15},
		{"LD (nn),BC", a::IMX, &c::LDNNDD, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 0", a::IMP, &c::IM0, 8},
		{"ADD I,A", a::REG, &c::LDIA, 9},
		{"IN C,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),C", a::IMP, &c::OUTCR, 12},
		{"ADC HL,BC", a::IMP, &c::ADCHLSS, 15},
		{"LD BC,(nn)", a::IMM, &c::LDDDFNN, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETI", a::IMP, &c::RETI, 14},
		{"IM 0", a::IMP, &c::IM0, 8},
		{"LD R,A", a::REG, &c::LDRA, 9},
		{"IN D,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),D", a::IMP, &c::OUTCR, 12},
		{"SBC HL,DE", a::IMP, &c::SBCHLSS, 15},
		{"LD (nn),DE", a::IMX, &c::LDNNDD, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 1", a::IMP, &c::IM1, 8},
		{"LD A,I", a::REG, &c::LDAI, 9},
		{"IN D,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),E", a::IMP, &c::OUTCR, 12},
		{"ADC HL,DE", a::IMP, &c::ADCHLSS, 15},
		{"LD DE,(nn)", a::IMX, &c::LDDDFNN, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 2", a::IMP, &c::IM2, 8},
		{"LD A,R", a::REG, &c::LDAR, 9},
		{"IN H,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),H", a::IMP, &c::OUTCR, 12},
		{"SBC HL,HL", a::IMP, &c::SBCHLSS, 15},
		{"LD (nn),HL", a::IMX, &c::LDNNDD, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 0", a::IMP, &c::IM0, 8},
		{"RRD", a::RGIHL, &c::RRD, 18},
		{"IN L,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),L", a::IMP, &c::OUTCR, 12},
		{"ADC HL,HL", a::IMP, &c::ADCHLSS, 15},
		{"LD HL,(nn)", a::IMX, &c::LDDDFNN, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 0", a::IMP, &c::IM0, 8},
		{"RLD", a::RGIHL, &c::RLD, 18},
		{"IN F,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),F", a::IMP, &c::OUTCR, 12},
		{"SBC HL,SP", a::IMP, &c::SBCHLSS, 15},
		{"LD (nn),SP", a::IMX, &c::LDNNDD, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 1", a::IMP, &c::IM1, 8},
		{"???", a::IMP, &c::XXX, 4},
		{"IN A,(C)", a::IMP, &c::INRC, 12},
		{"OUT (C),A", a::IMP, &c::OUTCR, 12},
		{"ADC HL,SP", a::IMP, &c::ADCHLSS, 15},
		{"LD SP,(nn)", a::IMX, &c::LDDDFNN, 20},
		{"NEG", a::IMP, &c::NEG, 8},
		{"RETN", a::IMP, &c::RETN, 14},
		{"IM 2", a::IMP, &c::IM2, 8},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LDI", a::IMP, &c::LDI, 16},
		{"CPI", a::IMP, &c::CPI, 16},
		{"INI", a::IMP, &c::INI, 16},
		{"OUTI", a::IMP, &c::OUTI, 16},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LDD", a::IMP, &c::LDD, 16},
		{"CPD", a::IMP, &c::CPD, 16},
		{"IND", a::IMP, &c::IND, 16},
		{"OUTD", a::IMP, &c::OUTD, 16},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LDIR", a::IMP, &c::LDIR, 16},
		{"CPIR", a::IMP, &c::CPIR, 16},
		{"INIR", a::IMP, &c::INIR, 16},
		{"OTIR", a::IMP, &c::OTIR, 16},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"LDDR", a::IMP, &c::LDDR, 16},
		{"CPDR", a::IMP, &c::CPDR, 16},
		{"INDR", a::IMP, &c::INDR, 16},
		{"OTDR", a::IMP, &c::OTDR, 16},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
		{"???", a::IMP, &c::XXX, 4},
	};

	cbInstructions =
	{
		{"RLC B", a::IMP, &c::RLCR, 8},
		{"RLC C", a::IMP, &c::RLCR, 8},
		{"RLC D", a::IMP, &c::RLCR, 8},
		{"RLC E", a::IMP, &c::RLCR, 8},
		{"RLC H", a::IMP, &c::RLCR, 8},
		{"RLC L", a::IMP, &c::RLCR, 8},
		{"RLC (HL)", a::RGIHL, &c::RLCHL, 15},
		{"RLC A", a::IMP, &c::RLCR, 8},
		{"RRC B", a::IMP, &c::RRCR, 8},
		{"RRC C", a::IMP, &c::RRCR, 8},
		{"RRC D", a::IMP, &c::RRCR, 8},
		{"RRC E", a::IMP, &c::RRCR, 8},
		{"RRC H", a::IMP, &c::RRCR, 8},
		{"RRC L", a::IMP, &c::RRCR, 8},
		{"RRC (HL)", a::RGIHL, &c::RRCHL, 15},
		{"RRC A", a::IMP, &c::RRCR, 8},
		{"RL B", a::IMP, &c::RLR, 8},
		{"RL C", a::IMP, &c::RLR, 8},
		{"RL D", a::IMP, &c::RLR, 8},
		{"RL E", a::IMP, &c::RLR, 8},
		{"RL H", a::IMP, &c::RLR, 8},
		{"RL L", a::IMP, &c::RLR, 8},
		{"RL (HL)", a::RGIHL, &c::RLHL, 15},
		{"RL A", a::IMP, &c::RLR, 8},
		{"RR B", a::IMP, &c::RRR, 8},
		{"RR C", a::IMP, &c::RRR, 8},
		{"RR D", a::IMP, &c::RRR, 8},
		{"RR E", a::IMP, &c::RRR, 8},
		{"RR H", a::IMP, &c::RRR, 8},
		{"RR L", a::IMP, &c::RRR, 8},
		{"RR (HL)", a::RGIHL, &c::RRHL, 15},
		{"RR A", a::IMP, &c::RRR, 8},
		{"SLA B", a::IMP, &c::SLAR, 8},
		{"SLA C", a::IMP, &c::SLAR, 8},
		{"SLA D", a::IMP, &c::SLAR, 8},
		{"SLA E", a::IMP, &c::SLAR, 8},
		{"SLA H", a::IMP, &c::SLAR, 8},
		{"SLA L", a::IMP, &c::SLAR, 8},
		{"SLA (HL)", a::RGIHL, &c::SLAHL, 15},
		{"SLA A", a::IMP, &c::SLAR, 8},
		{"SRA B", a::IMP, &c::SRAR, 8},
		{"SRA C", a::IMP, &c::SRAR, 8},
		{"SRA D", a::IMP, &c::SRAR, 8},
		{"SRA E", a::IMP, &c::SRAR, 8},
		{"SRA H", a::IMP, &c::SRAR, 8},
		{"SRA L", a::IMP, &c::SRAR, 8},
		{"SRA (HL)", a::RGIHL, &c::SRAHL, 15},
		{"SRA A", a::IMP, &c::SRAR, 8},
		{"SLS B", a::IMP, &c::SLSR, 8},
		{"SLS C", a::IMP, &c::SLSR, 8},
		{"SLS D", a::IMP, &c::SLSR, 8},
		{"SLS E", a::IMP, &c::SLSR, 8},
		{"SLS H", a::IMP, &c::SLSR, 8},
		{"SLS L", a::IMP, &c::SLSR, 8},
		{"SLS (HL)", a::RGIHL, &c::SLSHL, 15},
		{"SLS A", a::IMP, &c::SLSR, 8},
		{"SRL B", a::IMP, &c::SRLR, 8},
		{"SRL C", a::IMP, &c::SRLR, 8},
		{"SRL D", a::IMP, &c::SRLR, 8},
		{"SRL E", a::IMP, &c::SRLR, 8},
		{"SRL H", a::IMP, &c::SRLR, 8},
		{"SRL L", a::IMP, &c::SRLR, 8},
		{"SRL (HL)", a::RGIHL, &c::SRLHL, 15},
		{"SRL A", a::IMP, &c::SRLR, 8},
		{"BIT 0,B", a::IMP, &c::BITBR, 8},
		{"BIT 0,C", a::IMP, &c::BITBR, 8},
		{"BIT 0,D", a::IMP, &c::BITBR, 8},
		{"BIT 0,E", a::IMP, &c::BITBR, 8},
		{"BIT 0,H", a::IMP, &c::BITBR, 8},
		{"BIT 0,L", a::IMP, &c::BITBR, 8},
		{"BIT 0,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 0,A", a::IMP, &c::BITBR, 8},
		{"BIT 1,B", a::IMP, &c::BITBR, 8},
		{"BIT 1,C", a::IMP, &c::BITBR, 8},
		{"BIT 1,D", a::IMP, &c::BITBR, 8},
		{"BIT 1,E", a::IMP, &c::BITBR, 8},
		{"BIT 1,H", a::IMP, &c::BITBR, 8},
		{"BIT 1,L", a::IMP, &c::BITBR, 8},
		{"BIT 1,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 1,A", a::IMP, &c::BITBR, 8},
		{"BIT 2,B", a::IMP, &c::BITBR, 8},
		{"BIT 2,C", a::IMP, &c::BITBR, 8},
		{"BIT 2,D", a::IMP, &c::BITBR, 8},
		{"BIT 2,E", a::IMP, &c::BITBR, 8},
		{"BIT 2,H", a::IMP, &c::BITBR, 8},
		{"BIT 2,L", a::IMP, &c::BITBR, 8},
		{"BIT 2,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 2,A", a::IMP, &c::BITBR, 8},
		{"BIT 3,B", a::IMP, &c::BITBR, 8},
		{"BIT 3,C", a::IMP, &c::BITBR, 8},
		{"BIT 3,D", a::IMP, &c::BITBR, 8},
		{"BIT 3,E", a::IMP, &c::BITBR, 8},
		{"BIT 3,H", a::IMP, &c::BITBR, 8},
		{"BIT 3,L", a::IMP, &c::BITBR, 8},
		{"BIT 3,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 3,A", a::IMP, &c::BITBR, 8},
		{"BIT 4,B", a::IMP, &c::BITBR, 8},
		{"BIT 4,C", a::IMP, &c::BITBR, 8},
		{"BIT 4,D", a::IMP, &c::BITBR, 8},
		{"BIT 4,E", a::IMP, &c::BITBR, 8},
		{"BIT 4,H", a::IMP, &c::BITBR, 8},
		{"BIT 4,L", a::IMP, &c::BITBR, 8},
		{"BIT 4,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 4,A", a::IMP, &c::BITBR, 8},
		{"BIT 5,B", a::IMP, &c::BITBR, 8},
		{"BIT 5,C", a::IMP, &c::BITBR, 8},
		{"BIT 5,D", a::IMP, &c::BITBR, 8},
		{"BIT 5,E", a::IMP, &c::BITBR, 8},
		{"BIT 5,H", a::IMP, &c::BITBR, 8},
		{"BIT 5,L", a::IMP, &c::BITBR, 8},
		{"BIT 5,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 5,A", a::IMP, &c::BITBR, 8},
		{"BIT 6,B", a::IMP, &c::BITBR, 8},
		{"BIT 6,C", a::IMP, &c::BITBR, 8},
		{"BIT 6,D", a::IMP, &c::BITBR, 8},
		{"BIT 6,E", a::IMP, &c::BITBR, 8},
		{"BIT 6,H", a::IMP, &c::BITBR, 8},
		{"BIT 6,L", a::IMP, &c::BITBR, 8},
		{"BIT 6,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 6,A", a::IMP, &c::BITBR, 8},
		{"BIT 7,B", a::IMP, &c::BITBR, 8},
		{"BIT 7,C", a::IMP, &c::BITBR, 8},
		{"BIT 7,D", a::IMP, &c::BITBR, 8},
		{"BIT 7,E", a::IMP, &c::BITBR, 8},
		{"BIT 7,H", a::IMP, &c::BITBR, 8},
		{"BIT 7,L", a::IMP, &c::BITBR, 8},
		{"BIT 7,(HL)", a::RGIHL, &c::BITBHL, 12},
		{"BIT 7,A", a::IMP, &c::BITBR, 8},
		{"RES 0,B", a::IMP, &c::RESBR, 8},
		{"RES 0,C", a::IMP, &c::RESBR, 8},
		{"RES 0,D", a::IMP, &c::RESBR, 8},
		{"RES 0,E", a::IMP, &c::RESBR, 8},
		{"RES 0,H", a::IMP, &c::RESBR, 8},
		{"RES 0,L", a::IMP, &c::RESBR, 8},
		{"RES 0,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 0,A", a::IMP, &c::RESBR, 8},
		{"RES 1,B", a::IMP, &c::RESBR, 8},
		{"RES 1,C", a::IMP, &c::RESBR, 8},
		{"RES 1,D", a::IMP, &c::RESBR, 8},
		{"RES 1,E", a::IMP, &c::RESBR, 8},
		{"RES 1,H", a::IMP, &c::RESBR, 8},
		{"RES 1,L", a::IMP, &c::RESBR, 8},
		{"RES 1,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 1,A", a::IMP, &c::RESBR, 8},
		{"RES 2,B", a::IMP, &c::RESBR, 8},
		{"RES 2,C", a::IMP, &c::RESBR, 8},
		{"RES 2,D", a::IMP, &c::RESBR, 8},
		{"RES 2,E", a::IMP, &c::RESBR, 8},
		{"RES 2,H", a::IMP, &c::RESBR, 8},
		{"RES 2,L", a::IMP, &c::RESBR, 8},
		{"RES 2,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 2,A", a::IMP, &c::RESBR, 8},
		{"RES 3,B", a::IMP, &c::RESBR, 8},
		{"RES 3,C", a::IMP, &c::RESBR, 8},
		{"RES 3,D", a::IMP, &c::RESBR, 8},
		{"RES 3,E", a::IMP, &c::RESBR, 8},
		{"RES 3,H", a::IMP, &c::RESBR, 8},
		{"RES 3,L", a::IMP, &c::RESBR, 8},
		{"RES 3,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 3,A", a::IMP, &c::RESBR, 8},
		{"RES 4,B", a::IMP, &c::RESBR, 8},
		{"RES 4,C", a::IMP, &c::RESBR, 8},
		{"RES 4,D", a::IMP, &c::RESBR, 8},
		{"RES 4,E", a::IMP, &c::RESBR, 8},
		{"RES 4,H", a::IMP, &c::RESBR, 8},
		{"RES 4,L", a::IMP, &c::RESBR, 8},
		{"RES 4,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 4,A", a::IMP, &c::RESBR, 8},
		{"RES 5,B", a::IMP, &c::RESBR, 8},
		{"RES 5,C", a::IMP, &c::RESBR, 8},
		{"RES 5,D", a::IMP, &c::RESBR, 8},
		{"RES 5,E", a::IMP, &c::RESBR, 8},
		{"RES 5,H", a::IMP, &c::RESBR, 8},
		{"RES 5,L", a::IMP, &c::RESBR, 8},
		{"RES 5,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 5,A", a::IMP, &c::RESBR, 8},
		{"RES 6,B", a::IMP, &c::RESBR, 8},
		{"RES 6,C", a::IMP, &c::RESBR, 8},
		{"RES 6,D", a::IMP, &c::RESBR, 8},
		{"RES 6,E", a::IMP, &c::RESBR, 8},
		{"RES 6,H", a::IMP, &c::RESBR, 8},
		{"RES 6,L", a::IMP, &c::RESBR, 8},
		{"RES 6,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 6,A", a::IMP, &c::RESBR, 8},
		{"RES 7,B", a::IMP, &c::RESBR, 8},
		{"RES 7,C", a::IMP, &c::RESBR, 8},
		{"RES 7,D", a::IMP, &c::RESBR, 8},
		{"RES 7,E", a::IMP, &c::RESBR, 8},
		{"RES 7,H", a::IMP, &c::RESBR, 8},
		{"RES 7,L", a::IMP, &c::RESBR, 8},
		{"RES 7,(HL)", a::RGIHL, &c::RESBHL, 15},
		{"RES 7,A", a::IMP, &c::RESBR, 8},
		{"SET 0,B", a::IMP, &c::SETBR, 8},
		{"SET 0,C", a::IMP, &c::SETBR, 8},
		{"SET 0,D", a::IMP, &c::SETBR, 8},
		{"SET 0,E", a::IMP, &c::SETBR, 8},
		{"SET 0,H", a::IMP, &c::SETBR, 8},
		{"SET 0,L", a::IMP, &c::SETBR, 8},
		{"SET 0,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 0,A", a::IMP, &c::SETBR, 8},
		{"SET 1,B", a::IMP, &c::SETBR, 8},
		{"SET 1,C", a::IMP, &c::SETBR, 8},
		{"SET 1,D", a::IMP, &c::SETBR, 8},
		{"SET 1,E", a::IMP, &c::SETBR, 8},
		{"SET 1,H", a::IMP, &c::SETBR, 8},
		{"SET 1,L", a::IMP, &c::SETBR, 8},
		{"SET 1,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 1,A", a::IMP, &c::SETBR, 8},
		{"SET 2,B", a::IMP, &c::SETBR, 8},
		{"SET 2,C", a::IMP, &c::SETBR, 8},
		{"SET 2,D", a::IMP, &c::SETBR, 8},
		{"SET 2,E", a::IMP, &c::SETBR, 8},
		{"SET 2,H", a::IMP, &c::SETBR, 8},
		{"SET 2,L", a::IMP, &c::SETBR, 8},
		{"SET 2,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 2,A", a::IMP, &c::SETBR, 8},
		{"SET 3,B", a::IMP, &c::SETBR, 8},
		{"SET 3,C", a::IMP, &c::SETBR, 8},
		{"SET 3,D", a::IMP, &c::SETBR, 8},
		{"SET 3,E", a::IMP, &c::SETBR, 8},
		{"SET 3,H", a::IMP, &c::SETBR, 8},
		{"SET 3,L", a::IMP, &c::SETBR, 8},
		{"SET 3,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 3,A", a::IMP, &c::SETBR, 8},
		{"SET 4,B", a::IMP, &c::SETBR, 8},
		{"SET 4,C", a::IMP, &c::SETBR, 8},
		{"SET 4,D", a::IMP, &c::SETBR, 8},
		{"SET 4,E", a::IMP, &c::SETBR, 8},
		{"SET 4,H", a::IMP, &c::SETBR, 8},
		{"SET 4,L", a::IMP, &c::SETBR, 8},
		{"SET 4,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 4,A", a::IMP, &c::SETBR, 8},
		{"SET 5,B", a::IMP, &c::SETBR, 8},
		{"SET 5,C", a::IMP, &c::SETBR, 8},
		{"SET 5,D", a::IMP, &c::SETBR, 8},
		{"SET 5,E", a::IMP, &c::SETBR, 8},
		{"SET 5,H", a::IMP, &c::SETBR, 8},
		{"SET 5,L", a::IMP, &c::SETBR, 8},
		{"SET 5,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 5,A", a::IMP, &c::SETBR, 8},
		{"SET 6,B", a::IMP, &c::SETBR, 8},
		{"SET 6,C", a::IMP, &c::SETBR, 8},
		{"SET 6,D", a::IMP, &c::SETBR, 8},
		{"SET 6,E", a::IMP, &c::SETBR, 8},
		{"SET 6,H", a::IMP, &c::SETBR, 8},
		{"SET 6,L", a::IMP, &c::SETBR, 8},
		{"SET 6,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 6,A", a::IMP, &c::SETBR, 8},
		{"SET 7,B", a::IMP, &c::SETBR, 8},
		{"SET 7,C", a::IMP, &c::SETBR, 8},
		{"SET 7,D", a::IMP, &c::SETBR, 8},
		{"SET 7,E", a::IMP, &c::SETBR, 8},
		{"SET 7,H", a::IMP, &c::SETBR, 8},
		{"SET 7,L", a::IMP, &c::SETBR, 8},
		{"SET 7,(HL)", a::RGIHL, &c::SETBHL, 15},
		{"SET 7,A", a::IMP, &c::SETBR, 8},
	};

	ddcbInstructions =
	{
		{"RLC (IX+d),B", a::RELS, &c::RLCIXD, 23},
		{"RLC (IX+d),C", a::RELS, &c::RLCIXD, 23},
		{"RLC (IX+d),D", a::RELS, &c::RLCIXD, 23},
		{"RLC (IX+d),E", a::RELS, &c::RLCIXD, 23},
		{"RLC (IX+d),H", a::RELS, &c::RLCIXD, 23},
		{"RLC (IX+d),L", a::RELS, &c::RLCIXD, 23},
		{"RLC (IX+d)", a::RELS, &c::RLCIXD, 23},
		{"RLC (IX+d),A", a::RELS, &c::RLCIXD, 23},
		{"RRC (IX+d),B", a::RELS, &c::RRCIXD, 23},
		{"RRC (IX+d),C", a::RELS, &c::RRCIXD, 23},
		{"RRC (IX+d),D", a::RELS, &c::RRCIXD, 23},
		{"RRC (IX+d),E", a::RELS, &c::RRCIXD, 23},
		{"RRC (IX+d),H", a::RELS, &c::RRCIXD, 23},
		{"RRC (IX+d),L", a::RELS, &c::RRCIXD, 23},
		{"RRC (IX+d)", a::RELS, &c::RRCIXD, 23},
		{"RRC (IX+d),A", a::RELS, &c::RRCIXD, 23},
		{"RL (IX+d),B", a::RELS, &c::RLIXD, 23},
		{"RL (IX+d),C", a::RELS, &c::RLIXD, 23},
		{"RL (IX+d),D", a::RELS, &c::RLIXD, 23},
		{"RL (IX+d),E", a::RELS, &c::RLIXD, 23},
		{"RL (IX+d),H", a::RELS, &c::RLIXD, 23},
		{"RL (IX+d),L", a::RELS, &c::RLIXD, 23},
		{"RL (IX+d)", a::RELS, &c::RLIXD, 23},
		{"RL (IX+d),A", a::RELS, &c::RLIXD, 23},
		{"RR (IX+d),B", a::RELS, &c::RRIXD, 23},
		{"RR (IX+d),C", a::RELS, &c::RRIXD, 23},
		{"RR (IX+d),D", a::RELS, &c::RRIXD, 23},
		{"RR (IX+d),E", a::RELS, &c::RRIXD, 23},
		{"RR (IX+d),H", a::RELS, &c::RRIXD, 23},
		{"RR (IX+d),L", a::RELS, &c::RRIXD, 23},
		{"RR (IX+d)", a::RELS, &c::RRIXD, 23},
		{"RR (IX+d),A", a::RELS, &c::RRIXD, 23},
		{"SLA (IX+d),B", a::RELS, &c::SLAIXD, 23},
		{"SLA (IX+d),C", a::RELS, &c::SLAIXD, 23},
		{"SLA (IX+d),D", a::RELS, &c::SLAIXD, 23},
		{"SLA (IX+d),E", a::RELS, &c::SLAIXD, 23},
		{"SLA (IX+d),H", a::RELS, &c::SLAIXD, 23},
		{"SLA (IX+d),L", a::RELS, &c::SLAIXD, 23},
		{"SLA (IX+d)", a::RELS, &c::SLAIXD, 23},
		{"SLA (IX+d),A", a::RELS, &c::SLAIXD, 23},
		{"SRA (IX+d),B", a::RELS, &c::SRAIXD, 23},
		{"SRA (IX+d),C", a::RELS, &c::SRAIXD, 23},
		{"SRA (IX+d),D", a::RELS, &c::SRAIXD, 23},
		{"SRA (IX+d),E", a::RELS, &c::SRAIXD, 23},
		{"SRA (IX+d),H", a::RELS, &c::SRAIXD, 23},
		{"SRA (IX+d),L", a::RELS, &c::SRAIXD, 23},
		{"SRA (IX+d)", a::RELS, &c::SRAIXD, 23},
		{"SRA (IX+d),A", a::RELS, &c::SRAIXD, 23},
		{"SLS (IX+d),B", a::RELS, &c::SLSIXD, 23},
		{"SLS (IX+d),C", a::RELS, &c::SLSIXD, 23},
		{"SLS (IX+d),D", a::RELS, &c::SLSIXD, 23},
		{"SLS (IX+d),E", a::RELS, &c::SLSIXD, 23},
		{"SLS (IX+d),H", a::RELS, &c::SLSIXD, 23},
		{"SLS (IX+d),L", a::RELS, &c::SLSIXD, 23},
		{"SLS (IX+d)", a::RELS, &c::SLSIXD, 23},
		{"SLS (IX+d),A", a::RELS, &c::SLSIXD, 23},
		{"SRL (IX+d),B", a::RELS, &c::SRLIXD, 23},
		{"SRL (IX+d),C", a::RELS, &c::SRLIXD, 23},
		{"SRL (IX+d),D", a::RELS, &c::SRLIXD, 23},
		{"SRL (IX+d),E", a::RELS, &c::SRLIXD, 23},
		{"SRL (IX+d),H", a::RELS, &c::SRLIXD, 23},
		{"SRL (IX+d),L", a::RELS, &c::SRLIXD, 23},
		{"SRL (IX+d)", a::RELS, &c::SRLIXD, 23},
		{"SRL (IX+d),A", a::RELS, &c::SRLIXD, 23},
		{"BIT 0,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 0,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 0,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 0,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 0,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 0,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 0,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 0,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 1,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 1,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 1,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 1,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 1,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 1,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 1,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 1,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 2,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 2,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 2,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 2,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 2,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 2,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 2,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 2,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 3,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 3,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 3,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 3,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 3,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 3,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 3,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 3,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 4,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 4,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 4,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 4,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 4,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 4,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 4,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 4,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 5,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 5,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 5,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 5,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 5,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 5,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 5,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 5,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 6,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 6,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 6,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 6,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 6,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 6,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 6,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 6,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 7,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 7,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 7,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 7,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 7,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 7,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 7,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"BIT 7,(IX+d)", a::RELS, &c::BITBIXD, 20},
		{"RES 0,(IX+d),B", a::RELS, &c::RESBIXD, 23},
		{"RES 0,(IX+d),C", a::RELS, &c::RESBIXD, 23},
		{"RES 0,(IX+d),D", a::RELS, &c::RESBIXD, 23},
		{"RES 0,(IX+d),E", a::RELS, &c::RESBIXD, 23},
		{"RES 0,(IX+d),H", a::RELS, &c::RESBIXD, 23},
		{"RES 0,(IX+d),L", a::RELS, &c::RESBIXD, 23},
		{"RES 0,(IX+d)", a::RELS, &c::RESBIXD, 23},
		{"RES 0,(IX+d),A", a::RELS, &c::RESBIXD, 23},
		{"RES 1,(IX+d),B", a::RELS, &c::RESBIXD, 23},
		{"RES 1,(IX+d),C", a::RELS, &c::RESBIXD, 23},
		{"RES 1,(IX+d),D", a::RELS, &c::RESBIXD, 23},
		{"RES 1,(IX+d),E", a::RELS, &c::RESBIXD, 23},
		{"RES 1,(IX+d),H", a::RELS, &c::RESBIXD, 23},
		{"RES 1,(IX+d),L", a::RELS, &c::RESBIXD, 23},
		{"RES 1,(IX+d)", a::RELS, &c::RESBIXD, 23},
		{"RES 1,(IX+d),A", a::RELS, &c::RESBIXD, 23},
		{"RES 2,(IX+d),B", a::RELS, &c::RESBIXD, 23},
		{"RES 2,(IX+d),C", a::RELS, &c::RESBIXD, 23},
		{"RES 2,(IX+d),D", a::RELS, &c::RESBIXD, 23},
		{"RES 2,(IX+d),E", a::RELS, &c::RESBIXD, 23},
		{"RES 2,(IX+d),H", a::RELS, &c::RESBIXD, 23},
		{"RES 2,(IX+d),L", a::RELS, &c::RESBIXD, 23},
		{"RES 2,(IX+d)", a::RELS, &c::RESBIXD, 23},
		{"RES 2,(IX+d),A", a::RELS, &c::RESBIXD, 23},
		{"RES 3,(IX+d),B", a::RELS, &c::RESBIXD, 23},
		{"RES 3,(IX+d),C", a::RELS, &c::RESBIXD, 23},
		{"RES 3,(IX+d),D", a::RELS, &c::RESBIXD, 23},
		{"RES 3,(IX+d),E", a::RELS, &c::RESBIXD, 23},
		{"RES 3,(IX+d),H", a::RELS, &c::RESBIXD, 23},
		{"RES 3,(IX+d),L", a::RELS, &c::RESBIXD, 23},
		{"RES 3,(IX+d)", a::RELS, &c::RESBIXD, 23},
		{"RES 3,(IX+d),A", a::RELS, &c::RESBIXD, 23},
		{"RES 4,(IX+d),B", a::RELS, &c::RESBIXD, 23},
		{"RES 4,(IX+d),C", a::RELS, &c::RESBIXD, 23},
		{"RES 4,(IX+d),D", a::RELS, &c::RESBIXD, 23},
		{"RES 4,(IX+d),E", a::RELS, &c::RESBIXD, 23},
		{"RES 4,(IX+d),H", a::RELS, &c::RESBIXD, 23},
		{"RES 4,(IX+d),L", a::RELS, &c::RESBIXD, 23},
		{"RES 4,(IX+d)", a::RELS, &c::RESBIXD, 23},
		{"RES 4,(IX+d),A", a::RELS, &c::RESBIXD, 23},
		{"RES 5,(IX+d),B", a::RELS, &c::RESBIXD, 23},
		{"RES 5,(IX+d),C", a::RELS, &c::RESBIXD, 23},
		{"RES 5,(IX+d),D", a::RELS, &c::RESBIXD, 23},
		{"RES 5,(IX+d),E", a::RELS, &c::RESBIXD, 23},
		{"RES 5,(IX+d),H", a::RELS, &c::RESBIXD, 23},
		{"RES 5,(IX+d),L", a::RELS, &c::RESBIXD, 23},
		{"RES 5,(IX+d)", a::RELS, &c::RESBIXD, 23},
		{"RES 5,(IX+d),A", a::RELS, &c::RESBIXD, 23},
		{"RES 6,(IX+d),B", a::RELS, &c::RESBIXD, 23},
		{"RES 6,(IX+d),C", a::RELS, &c::RESBIXD, 23},
		{"RES 6,(IX+d),D", a::RELS, &c::RESBIXD, 23},
		{"RES 6,(IX+d),E", a::RELS, &c::RESBIXD, 23},
		{"RES 6,(IX+d),H", a::RELS, &c::RESBIXD, 23},
		{"RES 6,(IX+d),L", a::RELS, &c::RESBIXD, 23},
		{"RES 6,(IX+d)", a::RELS, &c::RESBIXD, 23},
		{"RES 6,(IX+d),A", a::RELS, &c::RESBIXD, 23},
		{"RES 7,(IX+d),B", a::RELS, &c::RESBIXD, 23},
		{"RES 7,(IX+d),C", a::RELS, &c::RESBIXD, 23},
		{"RES 7,(IX+d),D", a::RELS, &c::RESBIXD, 23},
		{"RES 7,(IX+d),E", a::RELS, &c::RESBIXD, 23},
		{"RES 7,(IX+d),H", a::RELS, &c::RESBIXD, 23},
		{"RES 7,(IX+d),L", a::RELS, &c::RESBIXD, 23},
		{"RES 7,(IX+d)", a::RELS, &c::RESBIXD, 23},
		{"RES 7,(IX+d),A", a::RELS, &c::RESBIXD, 23},
		{"SET 0,(IX+d),B", a::RELS, &c::SETBIXD, 23},
		{"SET 0,(IX+d),C", a::RELS, &c::SETBIXD, 23},
		{"SET 0,(IX+d),D", a::RELS, &c::SETBIXD, 23},
		{"SET 0,(IX+d),E", a::RELS, &c::SETBIXD, 23},
		{"SET 0,(IX+d),H", a::RELS, &c::SETBIXD, 23},
		{"SET 0,(IX+d),L", a::RELS, &c::SETBIXD, 23},
		{"SET 0,(IX+d)", a::RELS, &c::SETBIXD, 23},
		{"SET 0,(IX+d),A", a::RELS, &c::SETBIXD, 23},
		{"SET 1,(IX+d),B", a::RELS, &c::SETBIXD, 23},
		{"SET 1,(IX+d),C", a::RELS, &c::SETBIXD, 23},
		{"SET 1,(IX+d),D", a::RELS, &c::SETBIXD, 23},
		{"SET 1,(IX+d),E", a::RELS, &c::SETBIXD, 23},
		{"SET 1,(IX+d),H", a::RELS, &c::SETBIXD, 23},
		{"SET 1,(IX+d),L", a::RELS, &c::SETBIXD, 23},
		{"SET 1,(IX+d)", a::RELS, &c::SETBIXD, 23},
		{"SET 1,(IX+d),A", a::RELS, &c::SETBIXD, 23},
		{"SET 2,(IX+d),B", a::RELS, &c::SETBIXD, 23},
		{"SET 2,(IX+d),C", a::RELS, &c::SETBIXD, 23},
		{"SET 2,(IX+d),D", a::RELS, &c::SETBIXD, 23},
		{"SET 2,(IX+d),E", a::RELS, &c::SETBIXD, 23},
		{"SET 2,(IX+d),H", a::RELS, &c::SETBIXD, 23},
		{"SET 2,(IX+d),L", a::RELS, &c::SETBIXD, 23},
		{"SET 2,(IX+d)", a::RELS, &c::SETBIXD, 23},
		{"SET 2,(IX+d),A", a::RELS, &c::SETBIXD, 23},
		{"SET 3,(IX+d),B", a::RELS, &c::SETBIXD, 23},
		{"SET 3,(IX+d),C", a::RELS, &c::SETBIXD, 23},
		{"SET 3,(IX+d),D", a::RELS, &c::SETBIXD, 23},
		{"SET 3,(IX+d),E", a::RELS, &c::SETBIXD, 23},
		{"SET 3,(IX+d),H", a::RELS, &c::SETBIXD, 23},
		{"SET 3,(IX+d),L", a::RELS, &c::SETBIXD, 23},
		{"SET 3,(IX+d)", a::RELS, &c::SETBIXD, 23},
		{"SET 3,(IX+d),A", a::RELS, &c::SETBIXD, 23},
		{"SET 4,(IX+d),B", a::RELS, &c::SETBIXD, 23},
		{"SET 4,(IX+d),C", a::RELS, &c::SETBIXD, 23},
		{"SET 4,(IX+d),D", a::RELS, &c::SETBIXD, 23},
		{"SET 4,(IX+d),E", a::RELS, &c::SETBIXD, 23},
		{"SET 4,(IX+d),H", a::RELS, &c::SETBIXD, 23},
		{"SET 4,(IX+d),L", a::RELS, &c::SETBIXD, 23},
		{"SET 4,(IX+d)", a::RELS, &c::SETBIXD, 23},
		{"SET 4,(IX+d),A", a::RELS, &c::SETBIXD, 23},
		{"SET 5,(IX+d),B", a::RELS, &c::SETBIXD, 23},
		{"SET 5,(IX+d),C", a::RELS, &c::SETBIXD, 23},
		{"SET 5,(IX+d),D", a::RELS, &c::SETBIXD, 23},
		{"SET 5,(IX+d),E", a::RELS, &c::SETBIXD, 23},
		{"SET 5,(IX+d),H", a::RELS, &c::SETBIXD, 23},
		{"SET 5,(IX+d),L", a::RELS, &c::SETBIXD, 23},
		{"SET 5,(IX+d)", a::RELS, &c::SETBIXD, 23},
		{"SET 5,(IX+d),A", a::RELS, &c::SETBIXD, 23},
		{"SET 6,(IX+d),B", a::RELS, &c::SETBIXD, 23},
		{"SET 6,(IX+d),C", a::RELS, &c::SETBIXD, 23},
		{"SET 6,(IX+d),D", a::RELS, &c::SETBIXD, 23},
		{"SET 6,(IX+d),E", a::RELS, &c::SETBIXD, 23},
		{"SET 6,(IX+d),H", a::RELS, &c::SETBIXD, 23},
		{"SET 6,(IX+d),L", a::RELS, &c::SETBIXD, 23},
		{"SET 6,(IX+d)", a::RELS, &c::SETBIXD, 23},
		{"SET 6,(IX+d),A", a::RELS, &c::SETBIXD, 23},
		{"SET 7,(IX+d),B", a::RELS, &c::SETBIXD, 23},
		{"SET 7,(IX+d),C", a::RELS, &c::SETBIXD, 23},
		{"SET 7,(IX+d),D", a::RELS, &c::SETBIXD, 23},
		{"SET 7,(IX+d),E", a::RELS, &c::SETBIXD, 23},
		{"SET 7,(IX+d),H", a::RELS, &c::SETBIXD, 23},
		{"SET 7,(IX+d),L", a::RELS, &c::SETBIXD, 23},
		{"SET 7,(IX+d)", a::RELS, &c::SETBIXD, 23},
		{"SET 7,(IX+d),A", a::RELS, &c::SETBIXD, 23},
	};

	fdcbInstructions =
	{
		{"RLC (IY+d),B", a::RELS, &c::RLCIYD, 23},
		{"RLC (IY+d),C", a::RELS, &c::RLCIYD, 23},
		{"RLC (IY+d),D", a::RELS, &c::RLCIYD, 23},
		{"RLC (IY+d),E", a::RELS, &c::RLCIYD, 23},
		{"RLC (IY+d),H", a::RELS, &c::RLCIYD, 23},
		{"RLC (IY+d),L", a::RELS, &c::RLCIYD, 23},
		{"RLC (IY+d)", a::RELS, &c::RLCIYD, 23},
		{"RLC (IY+d),A", a::RELS, &c::RLCIYD, 23},
		{"RRC (IY+d),B", a::RELS, &c::RRCIYD, 23},
		{"RRC (IY+d),C", a::RELS, &c::RRCIYD, 23},
		{"RRC (IY+d),D", a::RELS, &c::RRCIYD, 23},
		{"RRC (IY+d),E", a::RELS, &c::RRCIYD, 23},
		{"RRC (IY+d),H", a::RELS, &c::RRCIYD, 23},
		{"RRC (IY+d),L", a::RELS, &c::RRCIYD, 23},
		{"RRC (IY+d)", a::RELS, &c::RRCIYD, 23},
		{"RRC (IY+d),A", a::RELS, &c::RRCIYD, 23},
		{"RL (IY+d),B", a::RELS, &c::RLIYD, 23},
		{"RL (IY+d),C", a::RELS, &c::RLIYD, 23},
		{"RL (IY+d),D", a::RELS, &c::RLIYD, 23},
		{"RL (IY+d),E", a::RELS, &c::RLIYD, 23},
		{"RL (IY+d),H", a::RELS, &c::RLIYD, 23},
		{"RL (IY+d),L", a::RELS, &c::RLIYD, 23},
		{"RL (IY+d)", a::RELS, &c::RLIYD, 23},
		{"RL (IY+d),A", a::RELS, &c::RLIYD, 23},
		{"RR (IY+d),B", a::RELS, &c::RRIYD, 23},
		{"RR (IY+d),C", a::RELS, &c::RRIYD, 23},
		{"RR (IY+d),D", a::RELS, &c::RRIYD, 23},
		{"RR (IY+d),E", a::RELS, &c::RRIYD, 23},
		{"RR (IY+d),H", a::RELS, &c::RRIYD, 23},
		{"RR (IY+d),L", a::RELS, &c::RRIYD, 23},
		{"RR (IY+d)", a::RELS, &c::RRIYD, 23},
		{"RR (IY+d),A", a::RELS, &c::RRIYD, 23},
		{"SLA (IY+d),B", a::RELS, &c::SLAIYD, 23},
		{"SLA (IY+d),C", a::RELS, &c::SLAIYD, 23},
		{"SLA (IY+d),D", a::RELS, &c::SLAIYD, 23},
		{"SLA (IY+d),E", a::RELS, &c::SLAIYD, 23},
		{"SLA (IY+d),H", a::RELS, &c::SLAIYD, 23},
		{"SLA (IY+d),L", a::RELS, &c::SLAIYD, 23},
		{"SLA (IY+d)", a::RELS, &c::SLAIYD, 23},
		{"SLA (IY+d),A", a::RELS, &c::SLAIYD, 23},
		{"SRA (IY+d),B", a::RELS, &c::SRAIYD, 23},
		{"SRA (IY+d),C", a::RELS, &c::SRAIYD, 23},
		{"SRA (IY+d),D", a::RELS, &c::SRAIYD, 23},
		{"SRA (IY+d),E", a::RELS, &c::SRAIYD, 23},
		{"SRA (IY+d),H", a::RELS, &c::SRAIYD, 23},
		{"SRA (IY+d),L", a::RELS, &c::SRAIYD, 23},
		{"SRA (IY+d)", a::RELS, &c::SRAIYD, 23},
		{"SRA (IY+d),A", a::RELS, &c::SRAIYD, 23},
		{"SLS (IY+d),B", a::RELS, &c::SLSIYD, 23},
		{"SLS (IY+d),C", a::RELS, &c::SLSIYD, 23},
		{"SLS (IY+d),D", a::RELS, &c::SLSIYD, 23},
		{"SLS (IY+d),E", a::RELS, &c::SLSIYD, 23},
		{"SLS (IY+d),H", a::RELS, &c::SLSIYD, 23},
		{"SLS (IY+d),L", a::RELS, &c::SLSIYD, 23},
		{"SLS (IY+d)", a::RELS, &c::SLSIYD, 23},
		{"SLS (IY+d),A", a::RELS, &c::SLSIYD, 23},
		{"SRL (IY+d),B", a::RELS, &c::SRLIYD, 23},
		{"SRL (IY+d),C", a::RELS, &c::SRLIYD, 23},
		{"SRL (IY+d),D", a::RELS, &c::SRLIYD, 23},
		{"SRL (IY+d),E", a::RELS, &c::SRLIYD, 23},
		{"SRL (IY+d),H", a::RELS, &c::SRLIYD, 23},
		{"SRL (IY+d),L", a::RELS, &c::SRLIYD, 23},
		{"SRL (IY+d)", a::RELS, &c::SRLIYD, 23},
		{"SRL (IY+d),A", a::RELS, &c::SRLIYD, 23},
		{"BIT 0,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 0,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 0,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 0,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 0,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 0,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 0,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 0,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 1,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 1,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 1,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 1,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 1,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 1,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 1,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 1,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 2,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 2,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 2,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 2,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 2,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 2,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 2,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 2,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 3,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 3,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 3,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 3,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 3,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 3,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 3,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 3,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 4,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 4,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 4,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 4,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 4,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 4,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 4,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 4,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 5,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 5,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 5,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 5,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 5,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 5,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 5,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 5,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 6,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 6,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 6,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 6,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 6,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 6,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 6,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 6,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 7,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 7,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 7,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 7,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 7,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 7,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 7,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"BIT 7,(IY+d)", a::RELS, &c::BITBIYD, 20},
		{"RES 0,(IY+d),B", a::RELS, &c::RESBIYD, 23},
		{"RES 0,(IY+d),C", a::RELS, &c::RESBIYD, 23},
		{"RES 0,(IY+d),D", a::RELS, &c::RESBIYD, 23},
		{"RES 0,(IY+d),E", a::RELS, &c::RESBIYD, 23},
		{"RES 0,(IY+d),H", a::RELS, &c::RESBIYD, 23},
		{"RES 0,(IY+d),L", a::RELS, &c::RESBIYD, 23},
		{"RES 0,(IY+d)", a::RELS, &c::RESBIYD, 23},
		{"RES 0,(IY+d),A", a::RELS, &c::RESBIYD, 23},
		{"RES 1,(IY+d),B", a::RELS, &c::RESBIYD, 23},
		{"RES 1,(IY+d),C", a::RELS, &c::RESBIYD, 23},
		{"RES 1,(IY+d),D", a::RELS, &c::RESBIYD, 23},
		{"RES 1,(IY+d),E", a::RELS, &c::RESBIYD, 23},
		{"RES 1,(IY+d),H", a::RELS, &c::RESBIYD, 23},
		{"RES 1,(IY+d),L", a::RELS, &c::RESBIYD, 23},
		{"RES 1,(IY+d)", a::RELS, &c::RESBIYD, 23},
		{"RES 1,(IY+d),A", a::RELS, &c::RESBIYD, 23},
		{"RES 2,(IY+d),B", a::RELS, &c::RESBIYD, 23},
		{"RES 2,(IY+d),C", a::RELS, &c::RESBIYD, 23},
		{"RES 2,(IY+d),D", a::RELS, &c::RESBIYD, 23},
		{"RES 2,(IY+d),E", a::RELS, &c::RESBIYD, 23},
		{"RES 2,(IY+d),H", a::RELS, &c::RESBIYD, 23},
		{"RES 2,(IY+d),L", a::RELS, &c::RESBIYD, 23},
		{"RES 2,(IY+d)", a::RELS, &c::RESBIYD, 23},
		{"RES 2,(IY+d),A", a::RELS, &c::RESBIYD, 23},
		{"RES 3,(IY+d),B", a::RELS, &c::RESBIYD, 23},
		{"RES 3,(IY+d),C", a::RELS, &c::RESBIYD, 23},
		{"RES 3,(IY+d),D", a::RELS, &c::RESBIYD, 23},
		{"RES 3,(IY+d),E", a::RELS, &c::RESBIYD, 23},
		{"RES 3,(IY+d),H", a::RELS, &c::RESBIYD, 23},
		{"RES 3,(IY+d),L", a::RELS, &c::RESBIYD, 23},
		{"RES 3,(IY+d)", a::RELS, &c::RESBIYD, 23},
		{"RES 3,(IY+d),A", a::RELS, &c::RESBIYD, 23},
		{"RES 4,(IY+d),B", a::RELS, &c::RESBIYD, 23},
		{"RES 4,(IY+d),C", a::RELS, &c::RESBIYD, 23},
		{"RES 4,(IY+d),D", a::RELS, &c::RESBIYD, 23},
		{"RES 4,(IY+d),E", a::RELS, &c::RESBIYD, 23},
		{"RES 4,(IY+d),H", a::RELS, &c::RESBIYD, 23},
		{"RES 4,(IY+d),L", a::RELS, &c::RESBIYD, 23},
		{"RES 4,(IY+d)", a::RELS, &c::RESBIYD, 23},
		{"RES 4,(IY+d),A", a::RELS, &c::RESBIYD, 23},
		{"RES 5,(IY+d),B", a::RELS, &c::RESBIYD, 23},
		{"RES 5,(IY+d),C", a::RELS, &c::RESBIYD, 23},
		{"RES 5,(IY+d),D", a::RELS, &c::RESBIYD, 23},
		{"RES 5,(IY+d),E", a::RELS, &c::RESBIYD, 23},
		{"RES 5,(IY+d),H", a::RELS, &c::RESBIYD, 23},
		{"RES 5,(IY+d),L", a::RELS, &c::RESBIYD, 23},
		{"RES 5,(IY+d)", a::RELS, &c::RESBIYD, 23},
		{"RES 5,(IY+d),A", a::RELS, &c::RESBIYD, 23},
		{"RES 6,(IY+d),B", a::RELS, &c::RESBIYD, 23},
		{"RES 6,(IY+d),C", a::RELS, &c::RESBIYD, 23},
		{"RES 6,(IY+d),D", a::RELS, &c::RESBIYD, 23},
		{"RES 6,(IY+d),E", a::RELS, &c::RESBIYD, 23},
		{"RES 6,(IY+d),H", a::RELS, &c::RESBIYD, 23},
		{"RES 6,(IY+d),L", a::RELS, &c::RESBIYD, 23},
		{"RES 6,(IY+d)", a::RELS, &c::RESBIYD, 23},
		{"RES 6,(IY+d),A", a::RELS, &c::RESBIYD, 23},
		{"RES 7,(IY+d),B", a::RELS, &c::RESBIYD, 23},
		{"RES 7,(IY+d),C", a::RELS, &c::RESBIYD, 23},
		{"RES 7,(IY+d),D", a::RELS, &c::RESBIYD, 23},
		{"RES 7,(IY+d),E", a::RELS, &c::RESBIYD, 23},
		{"RES 7,(IY+d),H", a::RELS, &c::RESBIYD, 23},
		{"RES 7,(IY+d),L", a::RELS, &c::RESBIYD, 23},
		{"RES 7,(IY+d)", a::RELS, &c::RESBIYD, 23},
		{"RES 7,(IY+d),A", a::RELS, &c::RESBIYD, 23},
		{"SET 0,(IY+d),B", a::RELS, &c::SETBIYD, 23},
		{"SET 0,(IY+d),C", a::RELS, &c::SETBIYD, 23},
		{"SET 0,(IY+d),D", a::RELS, &c::SETBIYD, 23},
		{"SET 0,(IY+d),E", a::RELS, &c::SETBIYD, 23},
		{"SET 0,(IY+d),H", a::RELS, &c::SETBIYD, 23},
		{"SET 0,(IY+d),L", a::RELS, &c::SETBIYD, 23},
		{"SET 0,(IY+d)", a::RELS, &c::SETBIYD, 23},
		{"SET 0,(IY+d),A", a::RELS, &c::SETBIYD, 23},
		{"SET 1,(IY+d),B", a::RELS, &c::SETBIYD, 23},
		{"SET 1,(IY+d),C", a::RELS, &c::SETBIYD, 23},
		{"SET 1,(IY+d),D", a::RELS, &c::SETBIYD, 23},
		{"SET 1,(IY+d),E", a::RELS, &c::SETBIYD, 23},
		{"SET 1,(IY+d),H", a::RELS, &c::SETBIYD, 23},
		{"SET 1,(IY+d),L", a::RELS, &c::SETBIYD, 23},
		{"SET 1,(IY+d)", a::RELS, &c::SETBIYD, 23},
		{"SET 1,(IY+d),A", a::RELS, &c::SETBIYD, 23},
		{"SET 2,(IY+d),B", a::RELS, &c::SETBIYD, 23},
		{"SET 2,(IY+d),C", a::RELS, &c::SETBIYD, 23},
		{"SET 2,(IY+d),D", a::RELS, &c::SETBIYD, 23},
		{"SET 2,(IY+d),E", a::RELS, &c::SETBIYD, 23},
		{"SET 2,(IY+d),H", a::RELS, &c::SETBIYD, 23},
		{"SET 2,(IY+d),L", a::RELS, &c::SETBIYD, 23},
		{"SET 2,(IY+d)", a::RELS, &c::SETBIYD, 23},
		{"SET 2,(IY+d),A", a::RELS, &c::SETBIYD, 23},
		{"SET 3,(IY+d),B", a::RELS, &c::SETBIYD, 23},
		{"SET 3,(IY+d),C", a::RELS, &c::SETBIYD, 23},
		{"SET 3,(IY+d),D", a::RELS, &c::SETBIYD, 23},
		{"SET 3,(IY+d),E", a::RELS, &c::SETBIYD, 23},
		{"SET 3,(IY+d),H", a::RELS, &c::SETBIYD, 23},
		{"SET 3,(IY+d),L", a::RELS, &c::SETBIYD, 23},
		{"SET 3,(IY+d)", a::RELS, &c::SETBIYD, 23},
		{"SET 3,(IY+d),A", a::RELS, &c::SETBIYD, 23},
		{"SET 4,(IY+d),B", a::RELS, &c::SETBIYD, 23},
		{"SET 4,(IY+d),C", a::RELS, &c::SETBIYD, 23},
		{"SET 4,(IY+d),D", a::RELS, &c::SETBIYD, 23},
		{"SET 4,(IY+d),E", a::RELS, &c::SETBIYD, 23},
		{"SET 4,(IY+d),H", a::RELS, &c::SETBIYD, 23},
		{"SET 4,(IY+d),L", a::RELS, &c::SETBIYD, 23},
		{"SET 4,(IY+d)", a::RELS, &c::SETBIYD, 23},
		{"SET 4,(IY+d),A", a::RELS, &c::SETBIYD, 23},
		{"SET 5,(IY+d),B", a::RELS, &c::SETBIYD, 23},
		{"SET 5,(IY+d),C", a::RELS, &c::SETBIYD, 23},
		{"SET 5,(IY+d),D", a::RELS, &c::SETBIYD, 23},
		{"SET 5,(IY+d),E", a::RELS, &c::SETBIYD, 23},
		{"SET 5,(IY+d),H", a::RELS, &c::SETBIYD, 23},
		{"SET 5,(IY+d),L", a::RELS, &c::SETBIYD, 23},
		{"SET 5,(IY+d)", a::RELS, &c::SETBIYD, 23},
		{"SET 5,(IY+d),A", a::RELS, &c::SETBIYD, 23},
		{"SET 6,(IY+d),B", a::RELS, &c::SETBIYD, 23},
		{"SET 6,(IY+d),C", a::RELS, &c::SETBIYD, 23},
		{"SET 6,(IY+d),D", a::RELS, &c::SETBIYD, 23},
		{"SET 6,(IY+d),E", a::RELS, &c::SETBIYD, 23},
		{"SET 6,(IY+d),H", a::RELS, &c::SETBIYD, 23},
		{"SET 6,(IY+d),L", a::RELS, &c::SETBIYD, 23},
		{"SET 6,(IY+d)", a::RELS, &c::SETBIYD, 23},
		{"SET 6,(IY+d),A", a::RELS, &c::SETBIYD, 23},
		{"SET 7,(IY+d),B", a::RELS, &c::SETBIYD, 23},
		{"SET 7,(IY+d),C", a::RELS, &c::SETBIYD, 23},
		{"SET 7,(IY+d),D", a::RELS, &c::SETBIYD, 23},
		{"SET 7,(IY+d),E", a::RELS, &c::SETBIYD, 23},
		{"SET 7,(IY+d),H", a::RELS, &c::SETBIYD, 23},
		{"SET 7,(IY+d),L", a::RELS, &c::SETBIYD, 23},
		{"SET 7,(IY+d)", a::RELS, &c::SETBIYD, 23},
		{"SET 7,(IY+d),A", a::RELS, &c::SETBIYD, 23},
	};

}
